### ISSUE TITLE
When removing a Virtual device from homey, homekit keeps track of the device.

### ISSUE THREAD

**Issue by rjbaat** [swttt/com.swttt.homekit#10]
When removing a Virtual device from homey, homekit keeps the device and this cant be removed. The result is that its not possible to remove the device from homey homekit page or from homekit in the apple home app. After doing a complete restart of homey. The app crashed and iphone cant connect to it anymore. I had to reinstall homekit app on homey to get it to work again.

**Comment by swttt** [comment]
Will add a listener for realtime events when devices are deleted, that when a device is deleted from Homey it gets deleted from Homeykit as well.

**Comment by swttt** [comment]
fixed in 1.0.10
