### ISSUE TITLE
[1.0.4]Osram Plugs are shown as a lights

### ISSUE THREAD

**Issue by andreasbeck** [swttt/com.swttt.homekit#11]
While the Osram Plugs are shown as a plug within Homey and within the HomeyKit, Apple Home shows them as a light.

1. The Osram plugs in devices
![osramplug_devices](https://user-images.githubusercontent.com/29104690/29247704-d038b640-800a-11e7-9495-13155c372b59.jpg)

2. The Osram plugs in HomeyKit
<img width="1357" alt="bildschirmfoto 2017-08-13 um 09 37 13" src="https://user-images.githubusercontent.com/29104690/29247723-1318c6d0-800b-11e7-907a-451baa9f5ba3.png">

3. The Osram plugs in Apple Home
As you can see in the Home App there are some TP-Link plugs recognised as a plug (e.g. Bad Infrarotheizung) , only the Osram plugs are shown as a light. I can't change the type of these devices within Home.

![home](https://user-images.githubusercontent.com/29104690/29247955-d8987acc-800b-11e7-8ce2-36104b55a65d.jpg)

Best Regards
Andreas

**Comment by swttt** [comment]
This seems an issue with the Lightify zigbee app, the socket is added as a plug there.
(See the app.json from the lightify zigbee repo)
`Line 30: "class": "light",`

Might be worth an issue in their repo tho ;)

**Comment by andreasbeck** [comment]
Hello,

thanks for this fast answer. just opened an issue to their repo. 

Best Regards
Andreas
