### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by Patrikgolfer** [swttt/com.swttt.homekit#110]
In V2 RC11 if a lamp is set to ex 85 % dimlevel in homey app you cant set it to 100% in homekit v3.00 until you change it to 100% in homeyapp. Not a big issue but just for info

**Comment by robertklep** [comment]
Does this happen for all lamps, or specific ones? Trying to work out if it's related to, for instance, a particular app on Homey.

**Comment by Patrikgolfer** [comment]
Hi
Seems it was a temporaliy issue . Tried all my fibaro dimmer2 an it work fine now . 
Ive Also tested Heimdal app and it perfect to control in HomeKit 

Thanks for a great app
/ Patrik

Skickat från min iPhone

**Comment by robertklep** [comment]
Okay, cool!
