### ISSUE TITLE
Crash in v3.0.1

### ISSUE THREAD

**Issue by robertklep** [swttt/com.swttt.homekit#112]
Another problem related to `capabilitiesObj` ([here](https://github.com/swttt/com.swttt.homekit/blob/beta/lib/devices/sensor.js#L10)). This time, it's not defined at all:

```
(node:20599) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.module.exports [as createSensor] (/lib/devices/sensor.js:10:27)
    at HomekitApp.addDevice (/app.js:194:42)
    at HomekitApp.startingServer (/app.js:67:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

I think that we should consider at least two fixes in `app.js`:

```
    for (let id in allDevices) {
      let device = allDevices[id];
      if (! device.ready) continue;
      ...
    }
...
	api.devices.on('device.update', async ({ id, ready }) => {
      if (! ready) return;
      if (id in knownDevices) return;
      ...
    });
```

And perhaps also all realtime event handlers.

**Comment by Strike2001** [comment]
what i know is that when a multisensor device added to homey , homeykit crashed till you disable the device in homeykitsettings , sometimes i must delete the multisensor complete. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by robertklep** [comment]
Should be fixed.
