### ISSUE TITLE
Making Scene Homekit

### ISSUE THREAD

**Issue by rwubbels** [swttt/com.swttt.homekit#113]
Hi,

Is it possible to make a scene in the Homekit app?

Iam facing soms issuses making flows/scenes with the Homey App, and in the Home (Woning) app i think its way easier to make some flows/scenes.

I tried it already a few months ago without succes.

Regards,
rwubbels

**Comment by robertklep** [comment]
Scenes can only be created in the Home/Woning app on iOS, and these cannot be "transferred" (or used) from the HomeKit app on Homey. However, you can of course use the devices that Homey exposes to HomeKit in scenes.
