### ISSUE TITLE
crash homekit 3.0.1. 

### ISSUE THREAD

**Issue by ypehille** [swttt/com.swttt.homekit#114]
the app for homekit keeps crashing it is yet updated 3.0.1

**Comment by robertklep** [comment]
Turn off the built-in (experimental) HomeKit implementation for Homey.

**Comment by robertklep** [comment]
Okay, if it's off, it's not the reason why it crashes.

Another problem that we ran in to is people uses thermostat devices that are not "complete" (Tado, I seem to remember). Do you have any of those devices?

**Comment by ypehille** [comment]
only Nefit easy witch i have not added only light and outlet switches

**Comment by robertklep** [comment]
Nefit should work. In that case, I don't know why it's crashing.

Can you send a crashlog to the developer? (I'm not on v2 yet so don't know if that option still exists)

**Comment by ypehille** [comment]
can i drop it here.

**Comment by robertklep** [comment]
sure!

**Comment by ypehille** [comment]
8b36c3b3-1e19-4ac8-adb0-4b1956d0b6e2

**Comment by robertklep** [comment]
The crashlog that belongs to that code doesn't actually contain any crashes :(

**Comment by ypehille** [comment]
the app keeps working added Kaku, fibaro, and neo coolcam switches. But crasshes when i ad a smartwares radiator kraan so that was the problem. another issue is that dimmable kaku switches are in home kit on/of switches and not dimmable in homekit

**Comment by robertklep** [comment]
Okay, good to know about the radiator kraan, I'll try and see if I can find out why it's failing. So for the time being, you can't control it through HomeKit.

Dimmable switches is not something that HomeKit itself supports. It's possible to "cheat" by telling HomeKit is not a switch (or an outlet), but a lamp. We will have to discuss if we want to implement such a cheat in HomeyKit too.
