### ISSUE TITLE
Geen connectie met homekit

### ISSUE THREAD

**Issue by Jdegroot1** [swttt/com.swttt.homekit#115]
Homekit vind de accessoires niet met code 20020200

13acb32d-3110-423f-923c-5afc954dd6a2

Homey 2.0.0

**Comment by Jdegroot1** [comment]
Heb experimental uitgezet en in de homeykit Tado uitgezet.

**Comment by Jdegroot1** [comment]
Hij heeft wel gedraaid maar daarna app opnieuw gestart na het verwijderen uit homekit en het uitzetten van experimental.

**Comment by robertklep** [comment]
Dat zou het probleem wel kunnen verklaren, mijn ervaring is dat iOS soms in de war raakt, zeker als je twee verschillende HomeKit implementaties op dezelfde hardware (Homey) draait.

Soms helpt het om je iPhone te rebooten, of WiFi uit en weer aan te schakelen. Of Homey te rebooten.

**Comment by robertklep** [comment]
Kreeg je de experimental versie wel aan de praat? En heb je die weer helemaal uit Home/Woning verwijderd?

**Comment by Jdegroot1** [comment]
Het lukt mij ook niet. Heb me hele homekit leeggehaald. 

Op 17 jan 2019 om 20:33 uur uur schreef Robert Klep <notifications@github.com>:

Kreeg je de experimental versie wel aan de praat? En heb je die weer helemaal uit Home/Woning verwijderd?

**Comment by robertklep** [comment]
We zitten te wachten op de goedkeuring voor een nieuwe beta release. Het probleem is dat de experimentele versie van Athom enorm in de weg zit van HomeyKit, en dat is hopelijk met die beta opgelost.

Ik hoop ook (maar dat is alleen maar hoop) dat dat problemen oplost voor mensen die eerst de experimental hebben gebruikt en nu naar HomeyKit overstappen.

**Comment by githubrst** [comment]
ja die werkte idd prima. Verwijdert kan bij mijn weten niet heb m wel uitgeschakeld. Heb overigens niet geprobeerd om de experimentele versie wederom in te schakelen om te kijken wat er gebeurt.

**Comment by robertklep** [comment]
@githubrst ik bedoel of je 'em in de Woning app op iOS hebt verwijderd. Daar moet je het hele "huis" verwijderen.

**Comment by githubrst** [comment]
Ah ok excuus :) ja dat heb ik idd meteen als aller eerste actie.

**Comment by githubrst** [comment]
Anders eerst maar even wachten op de beta versie wellicht lost dit t een en ander op. Snap de uitdagingen respect!

**Comment by githubrst** [comment]
Zojuist toch nog even gelezen wat je echt bedoelde 😀. Heb idd in de woning app de woning zelf verwijdert en hierna ziet ie m echt direct meteen 😀. Geweldig!!!!!
Dat was dus het geen wat ik nog niet had gedaan. Bedankt dit heeft t gefixed!!!

**Comment by Jdegroot1** [comment]
Heb dit bij mijn woning app ook geprobeerd maar helaas zonder goed resultaat..

**Comment by robertklep** [comment]
@Jdegroot1 toch even wachten op de beta dan, hopelijk dat die het wel voor je oplost. Helaas staat de beta al sinds woensdag te wachten op goedkeuring :(

**Comment by githubrst** [comment]
Just installed first impression looks good can now also use the dimming function again which whas broken.

Great job!!!!

**Comment by robertklep** [comment]
Thanks for testing, @githubrst!

**Comment by Jdegroot1** [comment]
3.0.3 werkte nog niet. 

Nu met 3.0.4 werkt het wel! Top weer, dankje. 

Op 21 jan 2019 om 19:22 uur uur schreef Robert Klep <notifications@github.com>:

Thanks for testing, @githubrst!
