### ISSUE TITLE
Z-wave dimmer becomes on/off socket in Homeykit

### ISSUE THREAD

**Issue by lindblomstefan** [swttt/com.swttt.homekit#120]
My Nexa/Everspring AD-146 z-wave dimmer ends up as an on/off socket in HomeKit. Before updating to 2.0 the AD-146 worked flawlessly in HomeKit. It works as supposed in the new Homey app.

**Comment by robertklep** [comment]
Hopefully the next beta will fix this.

**Comment by robertklep** [comment]
@lindblomstefan just released v3.0.3 as a beta, feel free to try (or wait until will promote it as stable, but not sure how long that will take).

**Comment by lindblomstefan** [comment]
@robertklep sorry for the delayed answer, kids... :) It works like a charm again with the AD-146 dimmer (which by the way is an affordable z-wave dimmer for around 36€ or 359:- SEK here in Sweden). I ran through all the other devices in my stack and it's thumbs up!
