### ISSUE TITLE
HomeKit app not working 

### ISSUE THREAD

**Issue by gizmodok** [swttt/com.swttt.homekit#121]
Hi,

After instelling New homey firmware 2.0 HomeKit app is not working there are just two devices and sill I don’t see theme on the HomeKit app on iPhone . Other devices are not visible in the HomeKit app they just vanished. Restart of the app doesn’t help.

I hope you can fine what’s wrong.

Please see log 6b37e1ab-f006-428d-a6ae-04af8a626619

Regards,
Kamil

**Comment by robertklep** [comment]
Hi Kamil!

Make sure that you have installed the latest version of the [Homeykit app](https://apps.athom.com/app/com.swttt.homekit). The log tells me that you're still using an old version.

**Comment by gizmodok** [comment]
I’ve installed a new version but the app is crashing see log

0331b54f-f617-4091-b393-2909192a6239

**Comment by robertklep** [comment]
It looks like you have a misbehaving thermostat device (perhaps a Tado?). For the time being, disable any thermostat devices in the settings of Homeykit. Hopefully we will have a fix for this soon.

**Comment by Strike2001** [comment]
the homeykit app crashed only if you add a Room Thermostat of Tado 
, the smart radiator devices can be added with homeykit [.](url
![5aa78476-68b3-4681-a570-764b7430b446](https://user-images.githubusercontent.com/5000021/51440281-c0c85400-1cc5-11e9-9697-6dfd0364dd01.jpeg)
)

**Comment by gizmodok** [comment]
Thanks I deleted thermostats. I don’t have tado thermostat but danfoss and popp thermostat. After deleting them everything looks ok.

**Comment by robertklep** [comment]
@gizmodok just released v3.0.3 as a beta, should hopefully fix the problem with your thermostat devices. If you don't feel comfortable installing a beta, you'll have to wait a bit longer until we promote it to stable.

**Comment by robertklep** [comment]
Sorry, not v3.0.3 but v3.0.4.

**Comment by robertklep** [comment]
Should be fixed as of 3.0.5
