### ISSUE TITLE
Multiple IOS device

### ISSUE THREAD

**Issue by vernerg** [swttt/com.swttt.homekit#122]
We have two iphones in the household but only one can be registered. After installed the homekit app in Homey only one ios device can be registered in the Home ios app. After the first phone is pared with Homey, the second one don't display the Home alternative.

**Comment by robertklep** [comment]
Try this:
- open the Home app on iOS
- press the house icon (top left)
- press "Home Settings..."
- under "Homes", select your home
- from there, you should be able to invite others from your household.

That method worked for me.

**Comment by vernerg** [comment]
Thank you!
That solved my problem.
