### ISSUE TITLE
Support multiple capability instances

### ISSUE THREAD

**Issue by robertklep** [swttt/com.swttt.homekit#123]
For example, the Aqara double switch device is exposed as one device with a single button. May not be trivial to implement.

**Comment by Sinled** [comment]
any progress on this issue?

I'm trying to migrate from sprut homekit plugin, which has stopped working after homey upgraded node version, and the only problem with current plugin is aqara double switches (i have them a lot =( ) not working correctly, 

but it worked fine in this plugin https://github.com/sprut666666/com.sprut.homekit2, you could add double switches as separate devices

**Comment by robertklep** [comment]
No progress on this issue, also no plans to implement it I'm afraid.

**Comment by Sinled** [comment]
I am not really familiar with homey and homekit ecosystem, but i think i can look into this problem, 
would you accept pr which adds support?

**Comment by robertklep** [comment]
As long as it doesn't break or change other behaviour, go ahead 👍🏻

**Comment by Sinled** [comment]
I've managed to add double ligths with quick and dirty solution, i'll take some time to develop more general approach
![IMG_5852](https://user-images.githubusercontent.com/1402135/83854600-9db60d00-a71f-11ea-984b-7d09f1e72b5c.png)

**Comment by robertklep** [comment]
Test version available: https://homey.app/a/com.swttt.homekit/test/
