### ISSUE TITLE
3.0.3 keeps crashing 

### ISSUE THREAD

**Issue by ProcessEngineer** [swttt/com.swttt.homekit#124]
Since the latest update the app constantly crashes :
2d48ed1d-d9d2-4ee1-a8b1-43f922d62141

**Comment by nhassink** [comment]
There is a known issue with (virtual) thermostats. Can you disable these in homeykit settings and try again?

**Comment by robertklep** [comment]
Might be any virtual device, in fact (switch, perhaps)?

**Comment by robertklep** [comment]
@ProcessEngineer v3.0.4 was published as a beta, and should fix the problem.

If you don't feel comfortable running beta versions, you'll have wait a few days.

**Comment by robertklep** [comment]
Should be fixed as of 3.0.5
