### ISSUE TITLE
Homeykit is er zomaar mee gestopt

### ISSUE THREAD

**Issue by Egberjo** [swttt/com.swttt.homekit#127]
Ik was bezig met het instellen van mijn Homey tot ik de melding kreeg dat de app Homeykit is gestopt.
Wat nu te doe, zonder dat ik HomeKit opnieuw moet instellen?

**Comment by robertklep** [comment]
Waarschijnlijk is er één apparaat dat roet in het eten gooit (een virtueel apparaat of een thermostaat, wellicht). Je kunt in de instellingen van Homeykit apparaten uitschakelen (zodat ze niet doorgegeven worden aan Homekit) en op die manier er achter zien te komen welk apparaat voor de problemen zorgt.

Hopelijk is dit probleem in een nieuwe versie opgelost.

**Comment by Egberjo** [comment]
Beste,
Ik was inderdaad met een virtual device bezig. Gelukkig heb ik het weten te corrigeren en werkt HomeKit weer naar behoren.
Dank voor de snelle reactie.
Groet Johan

Verstuurd vanaf mijn iPhone

**Comment by robertklep** [comment]
Should be fixed as of 3.0.5
