### ISSUE TITLE
Support for Satel Integra

### ISSUE THREAD

**Issue by mbnn** [swttt/com.swttt.homekit#129]
Hello,

Could you please support this homey plugin: https://apps.athom.com/app/org.myalarm.integra
With the built in homekit this will simply show as a button to turn alarm on or off. With Homekit plugin it does not show up at all. Thanks!

**Comment by robertklep** [comment]
It's strange that it uses "onoff" as a capability, because for alarm systems there is a specific capability "homealarm_state" that is more appropriate.

But I guess that adding support for "onoff" isn't that hard to implement, so I'll take a look.

**Comment by mbnn** [comment]
Thank you so much :) Just want to be able to quickly turn on or off the alarm, dont matter how :P Thx!

**Comment by robertklep** [comment]
As a workaround, you can use a virtual switch and some flows. The switch would show up in HomeKit, and with the flows you can turn on/off your alarm.

**Comment by mbnn** [comment]
@robertklep Tried it just now, the virtual device does not show up in Homeykit :( 

(I added Virtual device > button > alarm category) then added a flow that when Set to on it sets the Integra on and so on.

**Comment by robertklep** [comment]
It's probably the "alarm category" that is causing the problem. I don't know the specifics of how v2 virtual devices work (I assume that you're using that), but try using either an outlet/socket or a lamp (a device that "naturally" would have an on/off button).

**Comment by mbnn** [comment]
Yep now it works indeed :) Thx

**Comment by mbnn** [comment]
> It's strange that it uses "onoff" as a capability, because for alarm systems there is a specific capability "homealarm_state" that is more appropriate.
> 
> But I guess that adding support for "onoff" isn't that hard to implement, so I'll take a look.

Any update on this ? :)

**Comment by robertklep** [comment]
Just pushed some changes that should implement this. I can't test it myself because I don't run v2 and also don't have an alarm system, perhaps @nhassink has?

**Comment by mbnn** [comment]
Now just have to hope it will show up as beta on the appstore from athom :)

**Comment by mbnn** [comment]
Seems the beta is not on the appstore of Homey yet, any idea/update? :)

**Comment by robertklep** [comment]
3.0.7 is waiting for approval.

**Comment by mbnn** [comment]
Ok, tried 3.0.7 it shows the alarm panel yes in homekit, but clicking any of the buttons doesnt 'set' the alarm for some reason. 

When I set the alarm through a virtual button (as described before) it does show the status of the alarm. But it does not allow me to set it. Maybe otherwise simply make Satel Integra a button that also reflects current status (if off, show as off)?

**Comment by robertklep** [comment]
So to be clear: trying to enable/disable the alarm from Homekit (iOS) doesn't work? And when you change the state of the alarm on Homey (or through the Homey app), the state _is_ correctly reflected in Homekit iOS?

> Maybe otherwise simply make Satel Integra a button that also reflects current status (if off, show as off)?

I'd rather not add such specific exceptions to Homeykit.

**Comment by mbnn** [comment]
Exactly. So basically, it shows what the alarm is set now in Homekit but you cannot change it's state.

**Comment by mbnn** [comment]
Hi, this is still happening with the new 3.0.8, the alarm panel shows up in homekit but setting it to anything does not work (keeps saying disarming and so on). So basically, it shows what the alarm is set now in Homekit but you cannot change it's state. So now i still need a virtual button to set alarm on or off. With the built in Homekit implementation that is not necessary it simply shows the satel integra alarm as on/off button.

**Comment by robertklep** [comment]
I think I spotted a bug. Do you know how to use the CLI to install apps on Homey? If so, we can test it without having to do a (beta) release.

**Comment by mbnn** [comment]
Yes, that is no problem for me :)

**Comment by robertklep** [comment]
Cool, I just pushed a possible fix to the `beta` branch:

```
$ git clone -b beta --single-branch https://github.com/swttt/com.swttt.homekit
$ cd com.swttt.homekit
$ athom app run
```

**Comment by mbnn** [comment]
With this patch it works now (Home, Away, Night, Off buttons of Homekit alarm actually do set it), but it also immediatelly goes back to off (while alarm is being set in the background).

State Change - Integra Alarm - onoff - true
State Change - Integra Alarm - onoff - false
State Change - Integra Alarm - onoff - true
State Change - Integra Alarm - onoff - false
State Change - Integra Alarm - onoff - true
State Change - Integra Alarm - onoff - false

**Comment by robertklep** [comment]
You're not using Heimdall, are you?

**Comment by mbnn** [comment]
No, im purely using: https://github.com/DirkdeDraak/homey-integra-alarm/ << that one, no Heimdall here.

**Comment by robertklep** [comment]
The state changes (back to "false") are caused by the Satel Integra app, for some reason. It also has some logging enabled, so perhaps it might be useful to run that app through the CLI as well to see what it logs when you try to change the state (FWIW, I don't think that you can run two CLI sessions simultaneously, so you should install the Homeykit beta using `athom app install` and then `athom app run` the Satel app).

**Comment by mbnn** [comment]
Running satel integra app in debug i see this when i AWAY the alarm in homekit:

`2019-03-17 09:58:31 [log] [ManagerDrivers] [satelIntegra] [0] No armed partitions found => alarm is not armed.
2019-03-17 09:58:36 [log] [ManagerDrivers] [satelIntegra] [0] No armed partitions found => alarm is not armed.
2019-03-17 09:58:41 [log] [ManagerDrivers] [satelIntegra] [0] No armed partitions found => alarm is not armed.
2019-03-17 09:58:46 [log] [ManagerDrivers] [satelIntegra] [0] STATE CHANGE DETECTED to: true
2019-03-17 09:58:46 [log] [ManagerDrivers] [satelIntegra] [0] HomeAlarm state changed to: armed ( true )
[ '01', '00', '00', '00' ]
2019-03-17 09:58:51 [log] [ManagerDrivers] [satelIntegra] [0] No armed partitions found => alarm is not armed.`

**Comment by robertklep** [comment]
When I look at [the code that logs the _"No armed partitions found => alarm is not armed"_ message](https://github.com/DirkdeDraak/homey-integra-alarm/blob/master/drivers/satelIntegra/device.js#L241), I see it disabling the alarm again.

I have no idea why it does that, but it does explain why, after setting the alarm in Homekit, it reverts back to being disarmed again. It doesn't seem to be something that we can fix in Homeykit.

**Comment by mbnn** [comment]
Ok well at least your patch is good! and better cause at least it works now.

I recorded it on my iphone to show you what it does, video:

[ScreenRecording_03-17-2019 10-08-57.MP4.zip](https://github.com/swttt/com.swttt.homekit/files/2974963/ScreenRecording_03-17-2019.10-08-57.MP4.zip)

**Comment by mbnn** [comment]
So @robertklep could you pls push that tweak you made to the repo/app store of homey? :) Thx.

**Comment by robertklep** [comment]
I have, it's part of v3.0.8 (beta).

**Comment by robertklep** [comment]
Sorry, v3.0.9 I mean.

**Comment by mbnn** [comment]
Thanks :)
