### ISSUE TITLE
Nuki lock and some other devices no longer recognized ("Unknown")?

### ISSUE THREAD

**Issue by jordenc** [swttt/com.swttt.homekit#130]
First of all, thanks for a great app. The one on Homey I like best.

However, since the last update (I think) my Nest thermostat, Nest protect, virtual button and Nuki lock have yellow status "Unknown" in the settings (where you normally see Delete / Add).

The lock used to work perfectly and I am really missing this functionality now :)

**Comment by jordenc** [comment]
Yes, tried both.

![schermafbeelding 2019-01-31 om 11 43 32](https://user-images.githubusercontent.com/17727803/52049235-90967600-254d-11e9-993a-acac203ba332.png)

I am on 3.0.3, could it help to install the beta version instead?

**Comment by robertklep** [comment]
3.0.4 (the beta) hasn't changed anything relating to settings. There's a branch "cleanups" that you could try and run, but it's still WIP (although it has been running well, from what I understand).

The "unknown" state is strange and shouldn't happen. I'm not on v2 myself so it's difficult to try and work out why it's happening, and I don't think @nhassink has experienced this issue (?).

**Comment by jordenc** [comment]
Strange thing is that it worked well for a while. I think I might reinstall the app and start over. Just have to remove all my Hue lights again (which means a lot of Delete actions)

**Comment by jordenc** [comment]
I didn't do a thing but it now works. Closing :)

**Comment by robertklep** [comment]
magic! 🧙🏻‍♂️
