### ISSUE TITLE
i cannot use Homekit outside my wifi network

### ISSUE THREAD

**Issue by Piet1956** [swttt/com.swttt.homekit#135]
Yesterday I installed Homeykit.
I am not sure if I could use Homekit outside my network at that time, bu after the update it's definitely not working.
The only things that work are the things Apple supports, like Elgato stuff etc
Any ideas ?

**Comment by Piet1956** [comment]
Zeker, anders deden de Elgato’s en Hue’s het natuurlijk ook niet

Op 4 feb. 2019, om 18:28 heeft Robert Klep <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Do you have an AppleTV or an iPad that is set up as a Homekit hub? A HK hub is required to access your Homekit devices from outside your network.

**Comment by nhassink** [comment]
Bij mij duurt het even (1 a 2 min) voordat de devices buiten het netwerk zichtbaar zijn en ge-update zijn. Kan het zijn dat het na een tijdje wachten wel werkt?

**Comment by Piet1956** [comment]
Zal het morgen even uitproberen. Heb inderdaad niet zolang gewacht.
Bedankt alvast voor de input.

Gr Peter

Op 4 feb. 2019 om 18:52 heeft nhassink <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Bij mij duurt het even (1 a 2 min) voordat de devices buiten het netwerk zichtbaar zijn en ge-update zijn. Kan het zijn dat het na een tijdje wachten wel werkt?

**Comment by Piet1956** [comment]
Alles werkt weer.
Super, nogmaals bedankt voor je support


Op 4 feb. 2019 om 18:52 heeft nhassink <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Bij mij duurt het even (1 a 2 min) voordat de devices buiten het netwerk zichtbaar zijn en ge-update zijn. Kan het zijn dat het na een tijdje wachten wel werkt?
