### ISSUE TITLE
Boolean value not shown correctly in home app after restarting homey

### ISSUE THREAD

**Issue by moekdegroot** [swttt/com.swttt.homekit#14]
Hi swttt, first of all…great job on homeykit!

I just noticed that a boolean-bitflip device is always shown as “on” in the apple home app after restarting homey, even though the boolean was “false” before restarting homey.
I checked if homey was setting the boolean to true after the restart but in better logic the state is correct.
Are you experiencing the same?

Moek

**Comment by moekdegroot** [comment]
Forgot to mention, I'm on rc6.

**Comment by swttt** [comment]
Huhm...you sure the bit flip device shows the right value in the homey UI? Since it gets the new value on starting the app.

**Comment by moekdegroot** [comment]
I didn't check in the ui to be honest but did check in the better logic setting page. Can't check now because all devices are non responsive since this morning unfortunately. Hoping it's related to the degraded api message on status.athom.com.

**Comment by swttt** [comment]
Could you let me know if this is a BL issue? Since it should update based on the device card/value in the Homey UI as well.

**Comment by moekdegroot** [comment]
Hi Bas,

Yes I will. 
Hopefully this weekend I can experiment some more. 
The day after I made the issue homekit became unresponsive and all device were offline even though homeykit was functional. 
I was hoping installing rc8 would resolve it but it didn't. 
This weekend I'll delete and re-install homeykit and report back. 
Thx!

**Comment by moekdegroot** [comment]
Just tested some more and it doesn't look like a BL issue.
I made sure the boolean was off ( both in settings and UI) , restarted homey and checked if it was still off in settings and UI afterwards. It was in both places but on my phone it showed it was on. By the way, I just noticed that this also happens with my greenwave sockets. So I guess its a bug? Maybe it's socket related? Because when I added the boolean it was added as a socket and even though I changed it to a light in the homekit app maybe somewhere deep down its still seen as a socket? If there's anything else you need me to do/test let me know.
Thx!

**Comment by swttt** [comment]
I think it is related to the apps being loaded in batches now. So it could be (and i didn't test this yet) that HomeyKit gets loaded sooner then the (for example) Greenwace app. The devices that use the Greenwave driver aren't loaded so the API returns `undefined` where the socket does have a state (on/off etc.). I guess there isn't a realtime event emitted when the driver is loaded, and state is defined.

I could add a delay on boot to load the devices, but this is unwanted when just installing or restarting the app.
Going to check with Athom if this really could be the case tho...

**Comment by moekdegroot** [comment]
Hi Bas, I don't thats the case to be honest because Homeykit is always one of the last apps to load and Better Logic is loaded much earlier. 
At least in my setup. 
Maybe I should have mentioned that earlier, sorry.

**Comment by swttt** [comment]
And even the device drivers are initialized before HomeKit is loaded?

**Comment by moekdegroot** [comment]
That I'm not sure off to tell you the truth. 
I'll check tonight when I get home and let you know. 
Thx

**Comment by moekdegroot** [comment]
He Bas,
Sorry it took so long.
Just played around some more.
I'm sure all device drivers are loaded after a restart before homeykit is started because I can switch variables and sockets on and off while the settingspage of homeykit still gives the "not_found" message.
I also reinstalled homeykit and started from scratch and noticed that booleans and the greenwave sockets are shown as "on" in the home app even though they were "off" when I added them.
Anything else you need testing?

**Comment by swttt** [comment]
Will need to look deeper in this, i'll let you know!

**Comment by swttt** [comment]
actually a few things could have happened.

The capability could be undefined, homekit forces to set a value then even its not the correct value.
But this would mean there is actually something wrong with your device, but i doubt that...

Another thing could be that the devices changed it's status while it was still loading into HomeKit.
On a restart it's adding all devices one by one again.
In theory a wrong value could be pushed to homekit, where that value has been updated and homekit still holds the old value.

Do the bit flips and greenwave sockets update themselves using the realtime events?

**Comment by swttt** [comment]
Not sure if this still happens in the rewritten beta. If so please re-open.
