### ISSUE TITLE
Could you add the FAN device class?

### ISSUE THREAD

**Issue by Moskvitch** [swttt/com.swttt.homekit#140]
Mi Home app now allows control of Xiaomi Humidifiers and Air Purifiers.  However, only temp and humidity from built-in sensors data are shown in the Home app via Home(y)kit

Would be nice if we could control them from the Home app by using a fan-class device (multiple speeds I guess is not possible, but at least on/off)

Thanks

**Comment by robertklep** [comment]
Fan support in Homeykit exists for devices of class "fan" with capability "onoff", so my guess is that those devices aren't being created with either that class or that capability.

Can you post the device data from https://developer.athom.com/tools/devices (as a screenshot) here? I'm interested to see which class/capabilities it uses.

**Comment by Moskvitch** [comment]
![screen shot 2019-02-09 at 19 08 29](https://user-images.githubusercontent.com/11635627/52523081-80457000-2c9e-11e9-9bd3-6b5a777916df.png)

**Comment by robertklep** [comment]
That device class of "sensor" is the problem: Homeykit doesn't support "onoff" for sensors, mostly because Homekit itself doesn't support something like that :(

**Comment by Moskvitch** [comment]
Oh, I see, thanks.  From what you know, would there be any harm for the Mi Home app developer declaring it as a, say, switch?

**Comment by robertklep** [comment]
Switch would be problematic too, in the sense that _those_ don't support temperature and humidity in Homekit. Best solution would be to keep it a sensor, and set a virtual class of "fan" to it.

**Comment by Moskvitch** [comment]
Thx for your suggestions - will see if the Mi Home dev finds it feasible

**Comment by robertklep** [comment]
3.0.7 is waiting for approval, one of the changes is the implementation of `onoff` for `sensor` devices.

**Comment by robertklep** [comment]
3.0.7 is published as a beta.

**Comment by Moskvitch** [comment]
Yahooo!!! Thanks! Mi Humi 2 shown as an On/Off socket, with Temp and Humi levels also!  Thank you for indulging users’ (or rather this user’s) capricious requests!
