### ISSUE TITLE
Homey devices disappearing from automations and scenes

### ISSUE THREAD

**Issue by Moskvitch** [swttt/com.swttt.homekit#142]
I've experienced this for several days now - I find my Home(y)kit devices randomly:
* disappear from automations
* disappear from scenes
* re-gain their "Include in Favourites" status in the Home app (explicitly turned off by hand previously)
yet the keep their room assignments.

It's like they disappear from Homekit and them get re-added as new devices but keeping their Room assignments.  This happens without rebooting the Athom Homey or messing with the Homekit setup in any way.

Happen three times already, about once in one-two days

**Comment by robertklep** [comment]
Does the Homeykit app crash?

**Comment by Moskvitch** [comment]
No.  Another thing : not all devices exposed via Homeykit do that.  Only Xiaomi Mi (wifi, not Zigbee) and a virtual switch.  And even that may be a false lead, as those are the ones I added over the course last 10 days or so, so it could be a “time when added” problem with Apple Homekit itself acting up.  But if you could advise on things to look out for from the Homeykit perspective, I’d really appreciate this!
Thanks

**Comment by robertklep** [comment]
Apart from Homeykit crashing, I don't see why Homekit would decide that some devices should be removed or "reset".

You could try and start over by resetting Homeykit from the settings page ("Clear HomeKit Storage"), that would completely reset your Home setup (including room assignments).

Other than that, I don't have any suggestions for now :(

**Comment by Moskvitch** [comment]
Will try that, thanks. This had happened before with Homekit reverting to age-old configurations. Had to start fresh with a new ID to fix.  Or did I? :)
