### ISSUE TITLE
Homekit devices all enabled after new Homey Firmware

### ISSUE THREAD

**Issue by FrankRinkens** [swttt/com.swttt.homekit#143]
I installed HomeyKit and works fine, so far so good. I configured that not all devices in Homey are present in HomeKit. 

After installing Firmware update from Homey 2.04 yesterday, all devices where visible again in Homekit. 

Is it possible to keep track in a config "which devices are enabled or disabled for HomeKit". after reboot of Homey or Homeykit load that config file first. Would be helpfull, thanks.

**Comment by robertklep** [comment]
An upcoming beta update should hopefully fix that problem.

**Comment by robertklep** [comment]
3.0.7 is published as a beta, please try and see if it works better for you.

**Comment by FrankRinkens** [comment]
thanks @robertklep it works now for me.
