### ISSUE TITLE
Status «unkown»

### ISSUE THREAD

**Issue by jahnkenneth** [swttt/com.swttt.homekit#146]
In the settings for HomeyKit many of my devices have status «unknown» instead of «add» and «delete». 
Is this a known issue?

**Comment by robertklep** [comment]
Which version of Homeykit are you running? Try the latest beta (3.0.7).

**Comment by jahnkenneth** [comment]
Was not using the beta app on this Homey. 
The problem was solved when I installed it.
Good work!
