### ISSUE TITLE
session_expired

### ISSUE THREAD

**Issue by Veldkornet** [swttt/com.swttt.homekit#152]
HomeyKit: v3.0.10 - 29.03.19
Homey: v2.1.1

After restarting the HomeyKit app, going into settings gives the following error:

> Error: Er is een ombekende fout opgetreden [session_expired]

Diagnostic report: f8c80438-dedc-4cde-bf85-2013e4dfef76

**Comment by robertklep** [comment]
Known issue with Homey's firmware (other apps also suffer the same problem, so not specific to Homeykit), should be fixed in one of the upcoming updates.

**Comment by robertklep** [comment]
This should be fixed in firmware v2.1.2:
* [Apps SDK] Fix an issue that could cause apps to receive expired API tokens
