### ISSUE TITLE
Curtains support?

### ISSUE THREAD

**Issue by jordenc** [swttt/com.swttt.homekit#153]
My Slide curtains (https://apps.athom.com/app/nl.innovationinmotion.slide) are not visible in Homeykit (and therefor not in Homekit). I think they should be supported by Homekit though.

The device class is curtain, with capabilities windowcoverings_set

This works the same as "windowcoverings" with the "dim" capability.

Is it possible to add those to Homeykit? Or do I have to make changes on my end (the device class and capabilities are right now set as Emile of Athom recommended).

**Comment by robertklep** [comment]
I've added support for them in the current `beta` branch.

If you want to try running it from the CLI:
```
$ git clone --single-branch --branch beta https://github.com/swttt/com.swttt.homekit
$ cd com.swttt.homekit
$ athom app run
```

If not, you'll have to wait for a new beta version of the app to be published (hopefully this week, but it depends on time and Athom's approval speed).

**Comment by jordenc** [comment]
Thanks so much for the quick reaction! Installed the beta branch, but they weren't visible yet. Not sure why:

2019-04-24 11:15:55 [log] [HomekitApp] Not adding 'Logeerkamer' (shouldn't be paired)
2019-04-24 11:15:55 [log] [HomekitApp] Not adding 'Woonkamer Links' (shouldn't be paired)
2019-04-24 11:15:55 [log] [HomekitApp] Not adding 'Woonkamer Rechts' (shouldn't be paired)
2019-04-24 11:15:55 [log] [HomekitApp] Not adding 'Slaapkamer' (shouldn't be paired)

As far as I can see the code is correct and matching my settings in nl.innovationinmotion.slide app.json:
"class": "curtain",
"capabilities": ["windowcoverings_set"],

**Comment by robertklep** [comment]
It means the devices are not disabled (not exposed to Homekit) in the settings. Try enabling/adding them.

**Comment by jordenc** [comment]
They don't show up in the Homeykit devices list, somehow....

**Comment by robertklep** [comment]
Oh whoops, that's my fault, I forgot to add the code that would show those devices in the settings page. Fixed in the current `beta` branch.

**Comment by jordenc** [comment]
That's it, thanks so much! After adding almost immediately visible in Homekit on my iPhone, and it works flawlessly! <3

**Comment by robertklep** [comment]
Cool, thanks for testing!
