### ISSUE TITLE
Apple HomeKit don't discovery Homey after remove

### ISSUE THREAD

**Issue by stef1984** [swttt/com.swttt.homekit#155]
Hello. I’ve a little problem.

I’ve change the wifi password in my WIFI home, i’ve do the homey in recovery mode for change the password and now the homey in connected in the “new wifi”.
But after this, Apple HomeKit don’t discovery the Homey device.

I’ve remove the Homey device in Apple HomeKit and after this i’ve search a new device, but when i insert the code 200-20-200 for search the new device, this not found.

I’ve try to remove and reinstall the App HomeyKit, but is no work.

I’ve a similar problem wen i try with raspberry and homebridge with my older device Vera. If i don’t change the macadress in homebridge, the device don’t have discovering by the Apple HomeKit, because you found the older device( macadress) in memory and don0t associate newly.

Is possible is the similar problem?

Do you have a solution?

**Comment by robertklep** [comment]
You can try to clear the HomeKit storage in the Homeykit app settings.

**Comment by stef1984** [comment]
Thanks for the replay.

I’ve Found the problem.. I try to search a the Homey device in HomeKit in a different Wi-Fi network ( i’ve two Wi-Fi, one for local user And one specific for the homey and wireless device and security). I Connect mi iPhone in the security Wi-Fi and the device is fiume.

But now i see another problem. 

In HomeKit, if i’m Connect in this wifi, my device is found. if i try in 4G connetion, the device is not reachable. 

I remember after the change and Recovery homey for change wifi  connection, i use perfectly HomeKit outside the home with 4G. 
Is it possible? 
Thanks for the help

**Comment by robertklep** [comment]
Using HomeKit outside of your home requires a HomeKit Hub device (either an iPad that's always connected to power, or an AppleTV). The HomeyKit app itself cannot do anything to allow outside access to it, that's something that is purely managed by iOS itself.

**Comment by stef1984** [comment]
in the night I reflected and thought that the service with which I could use Homekit outside was possible because I have an AppleTV connected to my network, which had remained connected to the secondary network.
I then connected the AppleTV to the security wifi network and now everything works perfectly.

**Comment by robertklep** [comment]
Great! Thanks for the updates, I'll close this issue for now :)
