### ISSUE TITLE
Somfy roller shutters io not showing up

### ISSUE THREAD

**Issue by Stefan269** [swttt/com.swttt.homekit#159]
I have connected 3 Somfy RS100 io roller shutters to Homey via the TaHoma App. Works fine with Homey. Unfortunately, these shutters don’t show up in Homeykit at all.
Homey v2.1.2
Homey App v2.3.2.307
Tahoma App 1.5.4
Homeykit App 3.0.10/3.0.11

**Comment by robertklep** [comment]
Can you find one of those devices [here](https://developer.athom.com/tools/devices) and post the data related to the device here? Specifically the class and the capabilities.

**Comment by Stefan269** [comment]
Hi Robert,
yes, I can. Here is the requested info:

Property | Value
-- | --
ID | 28ffdc06-bcb7-4962-b51e-052a2c89157e
Class | blinds
Driver | homey:app:com.somfy.tahoma — io_roller_shutter
Ready | Yes
Available | Yes
Warning | No
Custom icon | No

Capability | Type | Value | Edit value | Last Updated
-- | -- | -- | -- | --
windowcoverings_state | enum | down | upidledown | 2 hours ago
windowcoverings_set | number | 0 |   | 3 minutes ago

Regards, Stefan.

**Comment by Stefan269** [comment]
Sorry, wrong button pressed. Issue still open.

**Comment by Wouter85** [comment]
I have the same issue would be great if support can be added!

I use this app for my whole home it works great!

**Comment by Wouter85** [comment]
Property	Value
ID	0b1023a5-1140-4295-a881-268f42f44141
Class	sunshade
Driver	homey:app:com.somfy.tahoma — io_vertical_exterior_blind
Ready	Yes
Available	Yes
Warning	No
Custom icon	No

Capabilities
Capability	Type	Value	Edit value	Last Updated
windowcoverings_state	enum	up	

2 weeks ago
windowcoverings_set	number	1	

38 seconds ago

**Comment by Stefan269** [comment]
Hi Robert,

thanks a lot for 3.0.12!
Yes, indeed this fixes my problem :-). I don’t know about Wouter85 but for my part this issue can be closed.

Thanks again, regards,
Stefan.

**Comment by polanus** [comment]
Hello Robert,

Thanks for releasing this new version. 

I've been watching this issue for quite a while, hoping that a new version would also let my Somfy IO outdoor horizontal awning appear in the HomeyKit app. Unfortunately for me this is not the case.

As the others did, I hereby also share my device specifications:
Property | Value
-- | --
ID | 787c573e-8512-4acb-ad28-e6b4c0e0dee7
Class | sunshade
Driver | homey:app:com.somfy.tahoma — io_horizontal_awning
Ready | Yes
Available | Yes
Warning | No
Custom icon | No

Capability | Type | Value | Edit value | Last Updated
-- | -- | -- | -- | --
windowcoverings_state | enum | up | upidledown | 3 months ago
windowcoverings_set | number | 1 |   | 3 months ago

Hopefully you would be able to consider this information in a solution of a future release!

Thanks in advance.

Philippe.

**Comment by robertklep** [comment]
@polanus geez, _another_ "window coverings" class 😜 I'll add it and push a new beta.

**Comment by robertklep** [comment]
@polanus I just published a new beta (3.0.13), try and see if that works for you.

**Comment by polanus** [comment]
Hi Robert,

Thanks a lot, It works! Will you create a new release for this?

Regards,
Philippe.

**Comment by robertklep** [comment]
I will promote it to stable, if that's what you mean :)

**Comment by polanus** [comment]
Indeed, thanks!

**Comment by polanus** [comment]
Hi Robert,

Would it be possible to promote the beta version to stable? Then I can switch back to the stable version and automatically get future versions installed on my Homey.

Thanks, Philippe.

**Comment by robertklep** [comment]
@polanus just promoted v3.0.13 to stable 👍🏻

**Comment by polanus** [comment]
Thanks! 👍
