### ISSUE TITLE
HomeKit accessoires not visible in Homey

### ISSUE THREAD

**Issue by EricMB73** [swttt/com.swttt.homekit#160]
Hi, 
Great app! All my homey-accessoires are in HomeKit now ! But I can’t seem to find accessoires that were already in HomeKit in Homey. So i can’t use HomeKit accessoires in flows.
Am I missing something?

Eric

**Comment by robertklep** [comment]
The HomeyKit app can only expose Homey apps _to_ HomeKit, but not the other way around. For that, you need an app that pretends to be a HomeKit client (like an iPhone or iPad), and AFAIK such an app doesn't exist for Homey.
