### ISSUE TITLE
Koogeek Homekit Lightstrip LS1

### ISSUE THREAD

**Issue by hendowe** [swttt/com.swttt.homekit#161]
Ondersteunt Homey ook de Koogeek Homekit producten zoals de Lightstrip LS1?

**Comment by robertklep** [comment]
Homeykit kan zelf geen Homekit-devices aansturen, het is voor iOS zélf een Homekit-device.

Er is zo te zien ook geen Koogeek-ondersteuning vanuit andere Homey-apps.

**Comment by hendowe** [comment]
Dus wanneer ik een ipad mini als de homekit controller aan de muur heb hangen, zal de homeykit hiermee communiceren en kun je homekit devices indirect benaderen.
Is deze conclusie correct?

Hendo

Verstuurd vanaf mijn iPhone
Hendo weernink
Managing director
Certsecurity bv
0492 782 150


Op 17 jun. 2019 om 17:51 heeft Robert Klep <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Homeykit kan zelf geen Homekit-devices aansturen, het is voor iOS zélf een Homekit-device.

Er is zo te zien ook geen Koogeek-ondersteuning vanuit andere Homey-apps.

**Comment by robertklep** [comment]
> Dus wanneer ik een ipad mini als de homekit controller aan de muur heb hangen, zal de homeykit hiermee communiceren en kun je homekit devices indirect benaderen.
Is deze conclusie correct?

Wat Homeykit doet is apparaten die gekoppeld zijn met Homey (die dus in de lijst van apparaten staan in de Homey app) beschikbaar maken via Homekit. Je stel dat je een Klikaanklikuit-schakelaar hebt die gekoppeld is met Homey, dan kun je die schakelaar via Homekit bedienen.

Homeykit kan zelf niet andere Homekit-apparaten bedienen (dus als je een apparaat hebt waar wél Homekit-ondersteuning maar géén Homey-ondersteuning voor is, dan kun je dat apparaat simpelweg niet via Homey of Homeykit bedienen).

**Comment by hendowe** [comment]
Bedankt
Hendo

Verstuurd vanaf mijn iPhone
Hendo weernink
Managing director
Certsecurity bv
0492 782 150


Op 17 jun. 2019 om 18:10 heeft Robert Klep <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Dus wanneer ik een ipad mini als de homekit controller aan de muur heb hangen, zal de homeykit hiermee communiceren en kun je homekit devices indirect benaderen.
Is deze conclusie correct?

Wat Homeykit doet is apparaten die gekoppeld zijn met Homey (die dus in de lijst van apparaten staan in de Homey app) beschikbaar maken via Homekit. Je stel dat je een Klikaanklikuit-schakelaar hebt die gekoppeld is met Homey, dan kun je die schakelaar via Homekit bedienen.

Homeykit kan zelf niet andere Homekit-apparaten bedienen (dus als je een apparaat hebt waar wél Homekit-ondersteuning maar géén Homey-ondersteuning voor is, dan kun je dat apparaat simpelweg niet via Homey of Homeykit bedienen).
