### ISSUE TITLE
Thermostat registreres as «off» when its on

### ISSUE THREAD

**Issue by danielfinans** [swttt/com.swttt.homekit#166]
I have added a Multireg (Heatit) Z-Wave thermostat v. 1.8 in Homey. When Homey puts the thermostat in «comfort» mode (which I believe is a mode the actual thermostat doesnt have) then its registrered as «of» in HomeKit. 
![BC46E31B-32CC-4F79-B09F-FB6593AC7864](https://user-images.githubusercontent.com/43092606/61169314-19352b80-a55c-11e9-8f40-6f105e544a41.png)
![18EE2938-8AA1-45E6-8DBB-EAA2182D0C6D](https://user-images.githubusercontent.com/43092606/61169315-19352b80-a55c-11e9-8c04-0883e825c9eb.jpeg)

**Comment by robertklep** [comment]
From what I can see, I don't think _any_ of the modes are supported, because the Heatit app uses a custom capability for it.
