### ISSUE TITLE
Xiaomi Aqara Vibration Sensor supported?

### ISSUE THREAD

**Issue by dilbert1982** [swttt/com.swttt.homekit#167]
Hey,

I recently bought a Xiaomi Vibration Sensor. Is this device supported by Homeykit? It did not appear in my home app or any other HomeKit apps (like Elgato Eve). 

If it is supported, do I have to take any further steps to use it in the home app?

regards

**Comment by robertklep** [comment]
The device isn't supported because it uses custom capabilities.

**Comment by dilbert1982** [comment]
will it be supported?

What about the other sensors from Xiaomi of the Aqara line? Flood sensor?

**Comment by robertklep** [comment]
It won't be supported, at least not soon(-ish). If the flood sensor also uses custom capabilities, the same will apply to that.

Some Xiaomi Aqara sensors _are_ supported, like the environmental sensor and (I think) the motion sensor.

**Comment by dilbert1982** [comment]
ok, thanks..

then I might have to get the Aqara Hub to integrate these sensors into homekit
