### ISSUE TITLE
Hue Dimmer Switch supported?

### ISSUE THREAD

**Issue by dilbert1982** [swttt/com.swttt.homekit#168]
Hey,

i am not able to use my Dimmer Switches with Homeykit in the Home App from Apple. Also I have a Z-Wave Switch from Devolo connected to my homey.

I think switches are supported? Am I doing anything wrong?

regards and thanks

**Comment by robertklep** [comment]
Can you go to https://developer.athom.com/tools/devices and	post the "Class" and "Capabilities" table from one of those switches?

**Comment by dilbert1982** [comment]
Hue Dimmer Switch: https://d.pr/free/i/5lcFFE

Devolo Light Switch: https://d.pr/free/i/vMYZn1

**Comment by robertklep** [comment]
Are those the only capabilities that the devices support? I only see `measure_battery`.

**Comment by dilbert1982** [comment]
i made a screenshot of everything... 

and yes that's what's shown under capabilities... kind of strange

**Comment by robertklep** [comment]
If those are the only ones, there's not a lot Homeykit can do with them :( (although, to be fair, HomeKit (the protocol) only has limited support for _input_ devices, which both your switches are).

**Comment by dilbert1982** [comment]
okay,

thought it would be possible to use them through Homey... If I connect the hue bridge direct to HomeKit, it is possible to use them....

**Comment by robertklep** [comment]
If Homey supports something doesn't necessarily mean that Home(y)Kit will support it, and vice versa. But what exactly do you want to do anyway?

There's a reason why HomeKit doesn't have a lot of support for input devices: the Home app on iOS is an input device itself. So you use your phone to switch on bulbs, just like you would use a physical dimmer switch to switch on bulbs. Both devices control the bulb, but not each other (because that wouldn't really make much sense).

**Comment by dilbert1982** [comment]
what I wanna do with it, quite simple... I have some lights I wanna control with it, without using my phone... (example in the bathroom) or use a light switch to turn everything off at night...

i am using my homey to get devices into the home app, that actually do not support HomeKit... then I might take my hue devices of the homey and connect them direct into HomeKit...

**Comment by robertklep** [comment]
So are the lights that you want to control supported by Homey? Or only by HomeKit?

**Comment by dilbert1982** [comment]
both... I have them with Homeykit in the Home App from apple... 

registered the Hue Bridge directly to Homekit, got my Dimmer Switches and can do now what I want to do without going over Homey with the Dimmer Switches...
