### ISSUE TITLE
Not compatible with Homey Firmware version 1.3.1

### ISSUE THREAD

**Issue by iamMichaelBanks** [swttt/com.swttt.homekit#17]
Hi,

I have a new Homey I have just installed, and would like to take a closer look at this app, but when I try to install it tells me it is incompatible with my Homey software version?...

Michael

**Comment by swttt** [comment]
Indeed, it's written based on SDK2. That means it only works on the (currently) experimental firmware.
You will need to wait until 1.5.0 hits the stable channel (i expect soon tho)
