### ISSUE TITLE
Icon update

### ISSUE THREAD

**Issue by IvoDerksen** [swttt/com.swttt.homekit#18]
Hey Bas! 
Great app, I've installed it and I've taken the liberty to adapt the current icon. Since it is only visible in settings I'd recommend to use the new icon.svg included in the zip file.
Of course this is up to you!

And I have a small question. Is it due to HomeKit that I can only access devices when I'm in the same network? Can this be changed, i.e. proxy through Homey. 

![image](https://user-images.githubusercontent.com/22196684/29685217-1660f070-8915-11e7-94d8-14aa5c8560bb.png)

[HomeyKit_icon.zip](https://github.com/swttt/com.swttt.homekit/files/1250031/HomeyKit_icon.zip)

**Comment by swttt** [comment]
Hey Ivo,

Cool thanks! Will add it to a next update.
Indeed it only works on your local network, this is how homekit is designed in general.
You can use an iPad or Apple TV to function as a hub(should be in the homekit settings somewhere), then you could access it from outside your home network as well and even create some automationt tasks.

**Comment by swttt** [comment]
Changed the icon in 1.0.12 😀 Thanks again!
