### ISSUE TITLE
Add support for Fyrtur

### ISSUE THREAD

**Issue by fishfisher** [swttt/com.swttt.homekit#180]
Would love to see support for Fyrtur blinds.
Let me know if I can be of any assistance!

<img width="670" alt="Skjermbilde 2019-09-29 kl  15 46 31" src="https://user-images.githubusercontent.com/5358905/65833401-5f369b80-e2d0-11e9-91ce-d2a5b514e84a.png">

Best regards,
Erik

**Comment by robertklep** [comment]
Should work with 3.0.12 and up.
