### ISSUE TITLE
Homekit not working anymore with firmware v4.2.0 rc2

### ISSUE THREAD

**Issue by Jdegroot1** [swttt/com.swttt.homekit#189]
Homekit stopped working after update to new firmware of homey. 

A massage to developer is send was the massage fromhomey on the timeline.

**Comment by robertklep** [comment]
I assume you mean firmware v4.2.0-rc.2?

There's a test version available that should work on that firmware: https://homey.app/a/com.swttt.homekit/test/

**Comment by DiedB** [comment]
Thanks, Robert!

**Comment by Jdegroot1** [comment]
Yes, works with the new software. Thank!
