### ISSUE TITLE
Virtual Devices (feature request)

### ISSUE THREAD

**Issue by Robinyoh** [swttt/com.swttt.homekit#19]
Like to use Virtual Devices from Arjan Kranenburg as a destination to trigger flows in Homey.

**Comment by swttt** [comment]
Huhm...depending on the device class. But actually should work for virtual devices that are sockets or lights.

**Comment by Robinyoh** [comment]
It is indeed working for sockets and light classes, i used the wrong device class. I used the "Modus" mode. You can close this issue. Thanks!
