### ISSUE TITLE
Can't remove socket

### ISSUE THREAD

**Issue by marklajer** [swttt/com.swttt.homekit#2]
**When I try to remove a Socket I get the following error:**

_Cannot read property 'toString' of undefined_

**The gui shows it's now deleted (I can add it again), but if I try that I get the following error:**

_Accessory ID already exists: 10_

**Comment by swttt** [comment]
Ye  seen that one happening before.
Still some parts in the settings page not working properly.
After you tried to add it again (it should say Added), and then remove it gives the same error again?

**Comment by marklajer** [comment]
@swttt Yes tried that. Doesn't work. See video clip :)

https://dsc.cloud/MALAJ/Screen-Recording-2017-08-03-12-58-01

**Comment by swttt** [comment]
Ofcourse you tried refreshing the page right? :)

But it looks like it's not passing the device object from the settings -> API -> app.js .

I'll try to add some logging functionality to the app to debug this kind of things without the need of running it within the CLI.

**Comment by marklajer** [comment]
@swttt Yes tried refresh ;) good idea about the debug functionality.

**Comment by swttt** [comment]
Just submitted 1.0.3 to the App Store, this version contains logs so we can see at least if it gets the device id :smile:

Please let me know once you updated. And what the result in the logs are.

**Comment by marklajer** [comment]
@swttt great Bas - waiting for release in appstore :)

**Comment by marklajer** [comment]
@swttt The problem is now solved after upgrading to 1.0.4 👍
