### ISSUE TITLE
On/off button on thermostats

### ISSUE THREAD

**Issue by runesig** [swttt/com.swttt.homekit#210]
This app is working great! I only do have a wish that you could also support the On / Off button in Homey for thermostats and set the corresponding HEAT or OFF 
![1459A793-BA59-4884-9ABC-60E9321423B2](https://user-images.githubusercontent.com/2069630/148036138-6330debb-19ff-4707-9caa-27babdcf8f8c.jpeg)
![ED1FD330-C9FD-4433-925A-7514CC6BB407](https://user-images.githubusercontent.com/2069630/148036143-b58d4b19-1bf0-4b0e-9b33-7b7edccc77b2.jpeg)
on the thermostat in the HomeKit app. Thanks for your great work!

**Comment by robertklep** [comment]
Thermostats in HomeKit don't have an on/off switch, they have a heating/cooling state. The developer of the Homey app has added a convenient way of setting that state to "heating" or "off" using an `onoff` capability, but that doesn't translate to HomeKit.

Also, this particular Homey developer has chose to use `onoff` to change the state, but another developer could use the same capability for something else entirely, so we cannot assume that every thermostat device with an `onoff` capability uses it to change the state.

**Comment by runesig** [comment]
OK, this is just a minor thing anyway and you have certainly thought this through. So I am closing this issue then. Thanks!
