### ISSUE TITLE
Forest curtains not showing up

### ISSUE THREAD

**Issue by jaccoh** [swttt/com.swttt.homekit#212]
I recently installed 4 forest curtain rails, they do not show up. Is there anything I need to do? or provide you with information or?

**Comment by robertklep** [comment]
Can you find one of the devices [on this page](https://tools.developer.homey.app/tools/devices) and report its capabilities to me?

**Comment by jaccoh** [comment]
Capability | Type | Value | Edit value | Last Updated
windowcoverings_state | enum | up | up idle down | 11 hours ago

It is Forest rails via RF not Z-Wave. So 3 values: "up", "idle" and "down"

**Comment by robertklep** [comment]
Ah sorry, I forgot to ask if you can also report the device class (`Class`) for it.

**Comment by jaccoh** [comment]
Class | blinds
Driver | homey:app:com.forest — shuttle

**Comment by jaccoh** [comment]
Ik ga hem installeren. I will try it out.

**Comment by robertklep** [comment]
Great, thank you for testing. I'll submit it to the app store for publication.
