### ISSUE TITLE
IOS 15.2.1 latency updating

### ISSUE THREAD

**Issue by Fryar27** [swttt/com.swttt.homekit#214]
Hello there, :)

Since I updated my iphone to ios 15.2.1, the equipment remains "updating" and cannot be used.
This behavior is only present when I am connected in wifi. When I switch to 4G and therefore go through my hub (my Homepod mini) everything works perfectly. Other devices with earlier IOS version work normally.

Apple having fixed a bug on homekit with this update, I strongly suspect that it had an impact.

I tried to reset the configuration of homeykit then to recreate it via my ipad in previous IOS version but my iphone in ios 15.2.1 remains in the same state. I've also tried to reset the network setting on my iPhone.

A clue ?

**Comment by robertklep** [comment]
I have no idea how I can help you, it sounds like Apple broke something.
