### ISSUE TITLE
Homebridge running in docker on Synology NAS

### ISSUE THREAD

**Issue by HQOFIQ** [swttt/com.swttt.homekit#217]
Hi everyone,
I have my Homey Pro working just fine with all connected devices but I cannot connect to Homebridge running as a docker container on my Synology NAS. The Version is 1.4.0 and Homebridge Dashboard shows everything thumbs up and fine. Homekit on my Homey Pro also finds that Homebridge when connecting (I can select it) and even asks for that unique PIN that Homebridge needs. But then it won't finish and will fail with an error stating "Network request failed" and that's the end of it then ... Any idea what I could do? I can reach Homebridge without any problems within my LAN (same that Homey Pro is connected to) ... Thanks in advance for any hint or solution!

**Comment by robertklep** [comment]
It sounds like your issue is with the [HomeKit Controller app](https://homey.app/a/de.karpienski.hkcontroller/) for Homey, and not with HomeyKit.

**Comment by HQOFIQ** [comment]
Hm, I installed HomeyKit on my Homey Pro (https://homey.app/de-at/app/com.swttt.homekit/HomeyKit/) and this is the forum I was linked to when asking for support ... what is the difference between HomeKit Controller App and HomeyKit? Sorry, but relatively new to Homey/Homekit ...

**Comment by HQOFIQ** [comment]
Oh, I see - same Icon, other usage scenario. My bad. Will contact the dev of HomeKit Controller then, thanks for the directions!
