### ISSUE TITLE
Tado devices not synchronized with HomeKit

### ISSUE THREAD

**Issue by Guidow1** [swttt/com.swttt.homekit#219]
I am using the Tado app that works fine in Homey but settings are not synchronized with Apple home using your app. For example if Tado shows Heating on HomeKit still shows heating off.

**Comment by robertklep** [comment]
Can you find the device [on this page](https://tools.developer.homey.app/tools/devices) and make a screenshot of the list of capabilities and their values for the device when it's heating and when it's off?

**Comment by Guidow1** [comment]
Hi Robert,

Here are the screenshots:

Turned on:


Turned off:


No change in HomeKit:

**Comment by robertklep** [comment]
Github doesn't show screenshots when you mail them, please add them to your comment on the website: https://github.com/swttt/com.swttt.homekit/issues/219#issuecomment-1066524605

**Comment by Guidow1** [comment]
Sorry I have just uploaded the files

**Comment by robertklep** [comment]
The device is using a custom capability (`power_mode`), and Homeykit doesn't support that.

I don't know why the developer of the Tado app didn't use one of the regular capabilities `onoff` or `thermostat_mode` for this. If they did, the device would have worked with Homeykit.

**Comment by Guidow1** [comment]
Thank you Robert for your quick response. I will talk to the Tado guys
