### ISSUE TITLE
Homekit not working anymore

### ISSUE THREAD

**Issue by guppi80** [swttt/com.swttt.homekit#221]
Hi since today homekit is not working anymore. Whole System restart ed. Any idea? Thanks

**Comment by robertklep** [comment]
What do you mean by "whole system restarted"?

**Comment by guppi80** [comment]
Restarted WLAN, Apple TV, Homey, homebridge app. Interestingly I can Turn on and off devices even though in the home app it says device cannot be reached. First time seen this. 



———————————————

**Comment by robertklep** [comment]
HomeyKit hasn't been updated in a while now, so it seems there should be another reason why it's not working anymore. Did you make any changes to your local network? Perhaps installed an experimental Homey firmware?
