### ISSUE TITLE
Delay after upgrading to 4.1.5

### ISSUE THREAD

**Issue by macca73** [swttt/com.swttt.homekit#222]
Hi Robert,

Just wanted to check if anyone else is having delays using Apple Homekit since the latest update to Homeykit 4.1.5.  Once I ask Siri to turn on/off a light, it takes approx. 15 seconds to action.  Homey app is working instantly.  I've rebooted Homey and Homey versions as per below.

Version 7.4.1 (Early 2018).
app version 6.11.3.920

**Comment by robertklep** [comment]
How busy is your Homey (in terms of CPU and RAM usage)? There were no changes made in HomeyKit that would cause a delay.

**Comment by macca73** [comment]
No changes to my setup besides Homeykit app update along with Homey update to 7.4.1.  Maybe something to do with Homey?

Cheers,
Paul

**Comment by robertklep** [comment]
That's why I asked how busy your Homey is 😁 There are some pretty significant changes in 7.4.1, some people have reported that Homey is taking up more RAM, for instance.

**Comment by jvanp** [comment]
I am verry sorry, but i have the ssme issue. Apple homekit responce after 15 sec. And mij Homey is alsno not busy. The Ram is also normal.

**Comment by robertklep** [comment]
Still, there have been no changes in Homeykit that could have caused these delays (the only changes that have been published have to do with working around all the issues in Homey's Web API that surfaced when Athom published Homey v7.4).

Homeykit gets its messages from iOS, and sends them to Homey's Web API. No (or hardly any) processing that could cause delays, or timers, or anything.

**Comment by jvanp** [comment]
strange. I have reset homey end the network, and the problem stils going. I think I go downgrading homey ore go to use the experimental homekit integration of Atom.

**Comment by robertklep** [comment]
You can't downgrade Homey.

If you know how to install Homey apps from the commandline I can explain how to install older versions of Homeykit so you can try, but the issue is that older versions may crash because of the aforementioned changes in firmware v7.4.

And to be clear: Homeykit crashing sounds like a Homeykit problem, but it will be crashing on problems within the Web API.

**Comment by jvanp** [comment]
thks

**Comment by macca73** [comment]
Hi Robert,

Homey support responded with instructions to power off honey, wait 15secs and then wait 15 minutes.

Everything back to normal now.

Apologies for taking up your time.  Love Homeykit.  Thankyou for all your constant support and updates.

Cheers,
Paul
