### ISSUE TITLE
Devices do not show up in Settings/HomeyKit

### ISSUE THREAD

**Issue by MarkvandenBroek** [swttt/com.swttt.homekit#23]
After installing and pairing the HomeyKit-app, devices do not show up in HomeyKit under Settings. I tried uninstalling and reinstalling, but that did not work either.

The 'spinner' keeps spinning. I was, however, able to add devices to the HomeyKit-app using the Chrome browser.

Homey-app (mac-version) 1.0.1, Firmware Homey 1.5.1, HomeyKit 1.0.8

**Comment by swttt** [comment]
Aah indeed the desktop app is restrictive when it comes to external frameworks etc.
Should have mentioned a browser is needed...
