### ISSUE TITLE
Aqara temperature sensor as motion sensor

### ISSUE THREAD

**Issue by ErikTbk** [swttt/com.swttt.homekit#230]
homeykit installed. 
now i see my aqara temperature sensors in homekit as motion sensors. Does anyone know how to get this as a temperature sensor?

thanks.

**Comment by robertklep** [comment]
Find the device here: https://tools.developer.homey.app/tools/devices, then post the "Class" and all capabilities here. If it has a capability called `alarm_motion`, then that's the reason why it's showing up as a motion sensor.

**Comment by ErikTbk** [comment]
hi, 
Class = sensor

Property | Value
-- | --
ID | 2410b9df-ed65-4f94-b9ec-e3d086e4fd03
Name | Temperatuur
Class | sensor
Driver | homey:app:com.xiaomi-mi — weather
Ready | Yes
Available | Yes
Warning | No
Custom icon | No

Key | Value
-- | --
token | "29933911-7954-40fd-8d18-7a1fbf9a19c4"


Key | Value
-- | --
zb_product_id | "lumi.weather"
zb_manufacturer_name | "LUMI"
temperature_offset | 0
temperature_decimals | "1"
humidity_offset | 0
humidity_decimals | "1"

**Comment by robertklep** [comment]
I'm missing the list of capabilities.

**Comment by ErikTbk** [comment]
I think I have found the problem. last update 3 months ago. 
same with my shelly temperature sensor.
See details:



Property | Value
-- | --
ID | 1d55123a-c834-4611-a38c-419f40ceec73
Name | Temperatuur woonkamer
Class | sensor
Driver | homey:app:cloud.shelly — shellyht
Ready | Yes
Available | Yes
Warning | No
Custom icon | Yes
; 

ID | Title | Type | Value | Set Value | Last Changed
-- | -- | -- | -- | -- | --
measure_humidity | Luchtvochtigheid | number | 64 |   | 13 minutes ago
measure_temperature | Temperatuur | number | 23.88 |   | 3 minutes ago
measure_battery | Accuniveau | number | 100 |   | 1 month ago
rssi | WiFi signaal | number | -40

**Comment by robertklep** [comment]
Not sure that I see the problem?
