### ISSUE TITLE
Aeotec Garage door controller stopped working

### ISSUE THREAD

**Issue by maceide** [swttt/com.swttt.homekit#232]
Yesterday my Aeotec garage door controller (gen5) stopped working in the app. Works fine in Homey, but when i try to access it from "home" on my iphone. It says that its not supported by the Home-app at the moment.

**Comment by robertklep** [comment]
Random issues are a part of Homey life, I'm afraid.

Homeykit hasn't been updated for a while so there's no reason why it would _suddenly_ stop working, other than something internal to Homey.
