### ISSUE TITLE
Homeykit stopped working after Homey update

### ISSUE THREAD

**Issue by HomeyUser** [swttt/com.swttt.homekit#234]
Homeykit stopped working after Homey update today. Seems new devices shows up in Home app, but with an exclamation mark and no communication.

**Comment by OlivierZal** [comment]
Works fine for me, most of the time restarting HomeyKit app solves the issue.

**Comment by HomeyUser** [comment]
Tried restarting both the app and Homey. No success 😢

**Comment by robertklep** [comment]
https://community.homey.app/t/something-not-working-after-a-homey-firmware-update-heres-the-solution/67824

**Comment by HomeyUser** [comment]
> https://community.homey.app/t/something-not-working-after-a-homey-firmware-update-heres-the-solution/67824

 Not sure what happened. Just started working again after a while. I’ll try the power adapter if it happens again. Thanks 👍

**Comment by robertklep** [comment]
Random things breaking (and then starting to work again) after firmware updates is normal with Homey 🙄
