### ISSUE TITLE
iOS 16 issues

### ISSUE THREAD

**Issue by timyboy12345** [swttt/com.swttt.homekit#235]
HomeyKit has been a little flakey lately, but it worked 95% of the time. Today, I updated to iOS 16.0 (and the matching tvOS and watchOS versions), but suddenly all devices are showing up "not responding". 

I haven't completely restarted my homey yet, but am doubtful this will fix the problem. 

I don't know whether this is a iOS 16 issue (and can be fixed with a homeykit update) or something else, but am creating this issue in the hopes of other people having the same problem (and reacting in the comments of this issue).

**Comment by robertklep** [comment]
I would still suggest rebooting Homey, or at least restarting HomeyKit.

I don't use HomeyKit extensively (because I don't use Homey) but after restarting the app the devices I do have exposed to HomeKit seem to be working on iOS 16.

**Comment by timyboy12345** [comment]
I restarted the homey, but that didn't seem to do anything. I then reset the hub, deleted it and added it again, and it seem to work for a couple of minutes. But I don't know if this was dummy data or actual data, so I don't know if the update is broken or the whole script. 

I think I'll just wait a couple of days to see if apple releases anything new, maybe the problem auto-fixes itself (I can hope, right?).

**Comment by timyboy12345** [comment]
Somehow, the latest Homey update (8.0.8) seems to have fixed the issue. Don't know why, don't know how, but I can once again control my lights with HomeKit.
