### ISSUE TITLE
Knx switch do not appears on HomeKit 

### ISSUE THREAD

**Issue by Mel-Stef** [swttt/com.swttt.homekit#236]
Dear,

I’m using your excellent HomeKit in jonction with KNX Homey app to expose all my KNX system to Homey and to Apple Home through your app.

A strange bug affect the “Switch” declared on KNX app. They don’t appears on HomeKit configuration. All others types (light, sensor, roller, etc..) are working like a charm.

Can you have a look to this bug ?

Kind regards.

Stefano

**Comment by robertklep** [comment]
Can you find the device in this list: https://tools.developer.homey.app/tools/devices

And then tell me its class and the list of capabilities that it supports.

**Comment by Mel-Stef** [comment]
Dear,

It is the problem ! the devices specified as « Switch » on KNX app do not appear on your list but all others yes.

This type of KNX device will not appear:


 


But for exemple a very similar KNX items will work:

     Light exemple: 


Kind regards.

Stefano Moriggia

**Comment by robertklep** [comment]
Can you post your screenshots [on the website](https://github.com/swttt/com.swttt.homekit/issues/236#issuecomment-1259387348) instead of mailing them? When you send them through e-mail, they don't appear on Github 😢

**Comment by Mel-Stef** [comment]
Done !

**Comment by robertklep** [comment]
@Mel-Stef sorry, the images are really small/scaled so very hard to see.

I don't really have to see how they look in the Homey app, it's more important for me to know what they look like [on the developer website](https://tools.developer.homey.app/tools/devices).

**Comment by Mel-Stef** [comment]
For exemple this KNX switch do not show up on HomeKit
![Capture d’écran 2022-09-30 à 09 02 26](https://user-images.githubusercontent.com/113628168/193210647-e09ea3f3-5c17-46a8-aac8-283920e71ea2.png)

**Comment by Mel-Stef** [comment]
or this other switch:

![Capture d’écran 2022-09-30 à 09 04 22](https://user-images.githubusercontent.com/113628168/193210968-2d100a10-c20d-405c-8593-8e5af0516a64.png)

**Comment by Mel-Stef** [comment]
In fact all declared type "Switch" on KNX app do not show up on HomeyKit. If for exemple I change to "Light" it will work (but annoying because it will appear like a lamp on Apple Home

**Comment by Mel-Stef** [comment]
Exemple of lamp (same binary action ON/OFF than a switch) working on HomeyKit:
![Capture d’écran 2022-09-30 à 09 08 40](https://user-images.githubusercontent.com/113628168/193211657-a22556f2-cda3-4228-8007-336dd5924752.png)

**Comment by robertklep** [comment]
It's a bit strange that they are marked as "remote", but it should be an easy fix to add support for them.

**Comment by Mel-Stef** [comment]
It will be top if you can fix that, I found a workaround for now with Homey Virtual switch but it is not a clean way to work

**Comment by robertklep** [comment]
I just published a test version of the app which should have support: https://homey.app/a/com.swttt.homekit/test/

**Comment by Mel-Stef** [comment]
Sorry the up light exemple is wrong (not a KNX device) but this one yes:
![Capture d’écran 2022-09-30 à 09 12 46](https://user-images.githubusercontent.com/113628168/193212576-e71962cf-e799-445d-8221-a8f366d254e7.png)

**Comment by Mel-Stef** [comment]
Dear Robert,
your test version is working. I could add all KNX “switch” type devices to home app now. 

Thank you very much for this ultra fast and effective support !

Kind regards

Stefano Moriggia

**Comment by robertklep** [comment]
Thanks for testing! I'll publish it as a new stable version as soon as possible.
