### ISSUE TITLE
Lock not changing state in HomeKit

### ISSUE THREAD

**Issue by fishfisher** [swttt/com.swttt.homekit#237]
Hi,
I have a lock (Yale Doorman L3) in Homey that I would like to expose to HomeKit.
It does show up in HomeKit via HomeyKit, however the state does not change and changing state via HomeKit does not work.
The device has following capabilities:
| ID               | Title      |
|------------------|------------|
| locked.custom    | Locked     |
| lock_unlock_open | State      |
| alarm_contact    | Door state |

Let me know if I can do anything to troubleshoot further.
Thanks!

**Comment by robertklep** [comment]
I've been working with a user on Slack to add support for this device. If you know how to run Homey apps from the command line, and know how to check out Github repositories: the current version of this repository should have support for locking/unlocking.

**Comment by fishfisher** [comment]
Quick response🙏!
Excellent, that did the trick.
Good work👍

**Comment by robertklep** [comment]
Thanks for testing! Please let me know after some more usage if everything works okay for you, so I can publish a new version of the app.

**Comment by fishfisher** [comment]
Sure thing👍
I'll get back to you after a bit of testing and everyday use.

**Comment by robertklep** [comment]
@fishfisher how has this version been working for you? If there aren't any major issues, I'd like to publish it as a new version to the app store 😊

**Comment by fishfisher** [comment]
@robertklep I have had some issues with the device itself so it's been a bit hard to test reliably. These issues are related to an unstable app for the device (Yale) and my experience is that the HomeyKit integration works well and as expected👍

**Comment by robertklep** [comment]
Thanks, I just published version 4.1.9 to the App Store!
