### ISSUE TITLE
HomeKit - homeykit verbinding werkt niet meer

### ISSUE THREAD

**Issue by Otterkop** [swttt/com.swttt.homekit#240]
Om mee te beginnen: ik ben ongelofelijk tevreden en blij met de HomeyKit app. Die heeft lange tijd erg goed gewerkt bij ons in huis. Sinds deze week heb ik issues :woozy_face:

Na installatie van een mesh systeem (linksys velop) was ik in eerste instantie Homey helemaal kwijt (en vanzelfsprekend reageerden daardoor ook mijn accessoires in HomeKit niet meer). Na terugsturen van dit systeem en het installeren van een andere versie mesh (ASUS zenwifi) is de situatie als volgt:

HomeKit app opnieuw geïnstalleerd
Storage geleegd
App herstart
Bridge opnieuw gekoppeld in HomeKit
alle accessoires opnieuw gekoppeld
… en dit (vanzelfsprekend?) meerdere keren uitgevoerd.

Helaas geen enkele respons van de accessoires in HomeKit (vanuit Homey Pro). Ik ben een beetje aan het einde van mijn opties. Wie heeft nog ideeën? Alvast bedankt!

**Comment by robertklep** [comment]
Even voor mijn duidelijkheid: je kunt Homey wel toevoegen op je iOS apparaat (en de Homey apparaten verschijnen ook in de Home app), maar je kunt niks besturen?

**Comment by Otterkop** [comment]
﻿Hi Robert

Dank je wel voor je reactie!

Ik kan de Homey als bridge toevoegen en alle accessoires toevoegen. Vanuit Homey kan ik alle apparaten gewoon aansturen. In HomeKit krijg ik alleen ‘geen reactie’ te zien. 

Ik heb een screen dump toegevoegd van mijn lampen in HomeKit.



Groet,

Hans Ottens

**Comment by robertklep** [comment]
Screenshots werken helaas niet als je via e-mail reageert, dat kan alleen [via de Github website](https://github.com/swttt/com.swttt.homekit/issues/240#issuecomment-1280350100).

Maar dit soort problemen is lastig te debuggen, ik vermoed dat het te maken heeft met je mesh systeem. Misschien dat het mogelijk is om voor je Homey een vast mesh point aan te wijzen?

**Comment by Otterkop** [comment]
Dag RobertIk heb m’n Homey Pro nu gekoppeld aan het centrale meshpunt (mijn HP) staat in de meterkast 😊. Ik ga afwachten wat er nu gebeurt. Heb jij evt nog een suggestie welke stappen te volgen om de boel zo clean mogelijk te configureren?Greetz, HansOp 17 okt. 2022 om 08:40 heeft Robert Klep ***@***.***> het volgende geschreven:﻿
Screenshots werken helaas niet als je via e-mail reageert, dat kan alleen via de Github website.
Maar dit soort problemen is lastig te debuggen, ik vermoed dat het te maken heeft met je mesh systeem. Misschien dat het mogelijk is om voor je Homey een vast mesh point aan te wijzen?

**Comment by robertklep** [comment]
Om zo schoon mogelijk opnieuw te beginnen kun je vanuit de app settings de storage resetten en eventueel een andere bridge identifier instellen. Maar dat eerste had je al gedaan.

**Comment by Otterkop** [comment]
Tx. Ik heb ook al een andere bridge identifier ingesteld … 😩.

Het wordt vermoedelijk een ouderwets trial and error circus. De home-app resetten heb ik niet veel zin in (alles eruit gooien en ding voor ding weer instellen). Ik verwacht overigens niet dat dat zou helpen.

Dank voor je hulp. Ik ga op onderzoek uit. En anders sparen voor een nieuwe Homey of zo - die kan ik met Ethernet koppelen (dacht ik). 

Cheers, Hans

**Comment by Otterkop** [comment]
even mijn laatste waarnemingen op een rij: 1. Ik merk dat de HomeyKit accessoires keurig worden toegevoegd; 2. Als ik een accessoire vervolgens bedien, krijg ik geen respons. Het lijkt alsof de HomeKit app geen signalen terug kan sturen naar Homey.

**Comment by Otterkop** [comment]
Nog een update: als ik HomeyKit deïnstalleer en het experiment HomeKit aanzet, gebeurt precies hetzelfde. Koppelen gaat goed, in eerste instantie werken knoppen maar gebeurt er niets, daarna (bv na herstarten Homey) werkt niets meer 🤯🤯

**Comment by robertklep** [comment]
Het HomeKit protocol gebruikt mDNS voor discovery (HomeyKit stuurt een bericht over het lokale netwerk naar iedereen die wil luisteren, met in dat bericht zaken als IP adres en TCP poort nummer waar iOS devices mee kunnen verbinden als ze gebruik willen maken van de HomeKit diensten op de Homey). Die verbinding werkt via het HTTP protocol.

Nu is het wel heel raar dat het koppelen gewoon lukt, maar vervolgens het aansturen en uitlezen niet, want beide acties maken gebruik van hetzelfde protocol. Omdat het voor beide HomeKit implementaties niet goed werkt is het probleem ook niet specifiek iets voor HomeyKit maar lijkt het te wijzen op een netwerkprobleem.

Wat ik nog kan verzinnen:
* voer een [PTP](https://community.homey.app/t/how-to-ptp/17304) uit.
* als je nog de originele power supply van Athom gebruikt voor je Homey: vervang die voor iets anders. Een fatsoenlijke USB oplader die minstens 2.3A kan leveren is goed.

Overigens nog hartelijk bedankt voor de donatie! 😊

**Comment by Otterkop** [comment]
Hi Robert. Graag gedaan. Het was mijn bedoeling om de donatie na mijn issue te doen. Zoals jij zelf aangeeft, is het niet de bedoeling om hier iets mee te bereiken. Ik dank je hartelijk voor alle tijd en hulp die je investeert. Ik zie je op de forums regelmatig mensen helpen. De donatie is een manier om iets tot uitdrukking te brengen wat te maken heeft met je betrokkenheid bij Homey. Thanks, Hans.

**Comment by Otterkop** [comment]
Hee Robert!! Het is opgelost. Op de een of andere manier kan de mesh (ethernet gekoppeld op het modem) de bekabelde delen van mijn netwerk (via switches op de router) niet vinden. Nu heb ik de switches omgeplugd naar het mesh hoofdknooppunt. En ... ik heb nu net een eerste lamp getest ... en toen Siri. Alles works weer ;-). Yesserdeyes!!

Jouw opmerking over de signalen deed het kwartje vallen. Dank je wel!!

**Comment by robertklep** [comment]
Mooi! Fijn dat het opgelost is 😁
