### ISSUE TITLE
No response after 4.2.0

### ISSUE THREAD

**Issue by kimwf** [swttt/com.swttt.homekit#243]
Hello. HomeyKit devices not responding in HK after updating to 4.2.0. When I try to downgrade to 4.1.10, HomeyKit app does not longer run on Homey. Disconnected AppleTV hub functionality, did not to anything. Native HK equipment and homebridge bridges running fine. Any tips for rectification?

BR
Kim F

**Comment by axelwathne** [comment]
Same here, no response on 4.2.0, downgrading fails. I had forgotten I was on the beta channel.

**Comment by robertklep** [comment]
If you want to downgrade, try removing the test version of app first, then install the regular version. A backup restore should also fix it (if not, the backup process of Homey is broken).

It wasn't my intention to block a downgrade, I'll have to look at why that happens 🤔

**Comment by robertklep** [comment]
The issue is caused by 4.2.0 using a different format to store internal data. The current stable version (4.1.10) will crash when it encounters files with the changed format. I'll have to check if the internal storage directory of an app is removed when you remove an app.

**Comment by axelwathne** [comment]
A homeykit reset or uninstall will lose all devices from HomeKit I take it? In that case a Homey restore is probably less work.

**Comment by robertklep** [comment]
A reset will certainly cause all devices to be lost. However, I would suggest trying to see if the problem doesn't solve itself (with 4.2.0), perhaps after a while or (if you use them) toggle Home hubs off/on.

**Comment by Sandor188** [comment]
@robertklep  Robert 

I use Homeykit and after the 4.2.0 update all devices are lost.
And the app crashes.

I made a screenshot : 

![0069267E-CEB0-4341-B357-31579A5CACDA](https://user-images.githubusercontent.com/35049051/198819104-09ac65ff-d935-4fe1-9e8a-111f9b901982.png)

**Comment by robertklep** [comment]
I will shortly push an updated test version of the app that will hopefully stop the crashes.

**Comment by robertklep** [comment]
Just pushed test version 4.2.1: https://homey.app/a/com.swttt.homekit/test/

**Comment by axelwathne** [comment]
No worries, Robert. We appreciate all your work, including that which breaks stuff 👍🏻

Restarting Apple hubs did not do the trick. I will try a restore.

**Comment by axelwathne** [comment]
Restore from backup did the trick, and I managed to switch to production channel before the app was updated. No repairing 45 devices today 💪🏻
