### ISSUE TITLE
Possible issue with future iOS 16.2 Home architecture upgrade

### ISSUE THREAD

**Issue by OlivierZal** [swttt/com.swttt.homekit#244]
Hi @robertklep,

I know it's not always pertinent to make conclusions based on a beta version, but maybe it could allow some anticipation: after last 16.2 (beta) update, the Home app asks for a mandatory architecture upgrade which breaks the integration with HomeyKit. I didn't succeeded in repairing it afterwards.

Just to let you know...

Kind regards

**Comment by robertklep** [comment]
See #242
