### ISSUE TITLE
Inconsistent Pairing code

### ISSUE THREAD

**Issue by doublehache** [swttt/com.swttt.homekit#246]
Hello there !
Don't know what give him to make it happy 🙃 
![image](https://user-images.githubusercontent.com/25353441/200195513-901ece4b-d927-4be3-8d23-6174a9265d28.png)

**Comment by robertklep** [comment]
The correct code is 20020200

**Comment by doublehache** [comment]
@robertklep thanks bro! Sorry was confused about new Apple Home formatting pairing code.

**Comment by robertklep** [comment]
No problem, I agree it's confusing that Apple changed the formatting (for no apparent reason).
