### ISSUE TITLE
Fibaro Door Sensor 

### ISSUE THREAD

**Issue by kevinpaulus** [swttt/com.swttt.homekit#249]
since the last update, my fibaro window sensors are displayed as switches. can you fix that please?

**Comment by robertklep** [comment]
HomeyKit hasn't been updated for some time now, which version do you mean specifically?

**Comment by kevinpaulus** [comment]
wow, thanks for the quick reply. it must have happened either here or after the homey update. the Aquara sensors are transmitted correctly..

**Comment by robertklep** [comment]
Can you find one of the wrongly displayed devices here: https://tools.developer.homey.app/tools/devices

And then post its Class, virtual class (if it has one) and its capabilities here.

**Comment by kevinpaulus** [comment]
The class is „Sensor“ and Capabilities „alarm_contact“ and „button.reconnect“
The devices come from the HomeAssistant Community App

**Comment by robertklep** [comment]
My guess is that the HomeAssistant app was updated and started adding the `button` capability to devices, which broke their integration with HomeyKit. I can't fix that without potentially breaking things for other apps/users.

I would suggest considering moving to my new [HomeKitty app](https://homey.app/a/name.klep.homekitty/) instead, which should not have any issues with this device.
