### ISSUE TITLE
Not working with tvOS 11 and iOS 11

### ISSUE THREAD

**Issue by bliekp** [swttt/com.swttt.homekit#25]
Not working on latest Apple software. I use the AppleTV (rev 4) as the hub and an iPhone 8 plus and / or iPad Air 2, both running iOS 11.0.1 as clients.

All devices are showing 'no response'...

**Comment by swttt** [comment]
Could it be that your removed a device that actually was added to homekit before?

**Comment by swttt** [comment]
Seems like a duplicate: https://github.com/swttt/com.swttt.homekit/issues/5
Please try version 1.0.11 and see if the problem still exists.
