### ISSUE TITLE
Homeykit compatible with new Apple HomeKit architecture?

### ISSUE THREAD

**Issue by thatsme24u** [swttt/com.swttt.homekit#250]
Hi
Can anybody tell if Homeykit will work after Apple releases its new architecture (and I apply this in my environment)
Thanks!

**Comment by robertklep** [comment]
https://community.homey.app/t/app-pro-homeykit/70469#note-on-home-changes-in-ios-162-4

But Apple has disabled upgrades to the new architecture due to many issues, so all we can do is way to see if anything significant changes when they enable upgrades again.
