### ISSUE TITLE
Daikin Onecta - Homey - Siri

### ISSUE THREAD

**Issue by WWGG12** [swttt/com.swttt.homekit#253]
I have a daikin Perfera (FVXM50) connected through the Daikin ONECTA app. 
It is setup in my.homey and everything works like a chime when I want to control the airco.

I also have the Homekit app setup in that homey. 
I can control my temperatures from my Home app (or Siri) but that where it ends. I cannot change the mode of the airco or even switch it on or off by homekit or Siri

**Comment by robertklep** [comment]
Development of HomeyKit has stopped, [please read this](https://community.homey.app/t/app-pro-homeykit/70469#important-this-app-is-deprecated-2) for more information and an alternative.
