### ISSUE TITLE
Homey pro 2023

### ISSUE THREAD

**Issue by Gitano22** [swttt/com.swttt.homekit#256]
I'm having trouble installing homeykit and smartthings because they're not updated to homey pro

**Comment by robertklep** [comment]
I don't know about Smartthings, but HomeyKit is available for Homey Pro 2023 if you install the test version: https://homey.app/a/com.swttt.homekit/test/

However, I would strongly recommend using the [HomeKitty](https://homey.app/a/name.klep.homekitty/) instead of HomeyKit.

**Comment by Gitano22** [comment]
With pro app i have the some problem

Gaetano Colavita
***@***.***
3899843731
Montescudo RN

Il giorno 5 ago 2023, alle ore 14:41, Robert Klep ***@***.***> ha scritto:

﻿

I don't know about Smartthings, but HomeyKit is available for Homey Pro 2023 if you install the test version: https://homey.app/a/com.swttt.homekit/test/

However, I would strongly recommend using the HomeKitty<https://homey.app/a/name.klep.homekitty/> instead of HomeyKit.

**Comment by robertklep** [comment]
> With pro app i have the some problem

I have no idea what that means 😢
