### ISSUE TITLE
Accessoires unreachable

### ISSUE THREAD

**Issue by mvancaulil** [swttt/com.swttt.homekit#258]
Beste heer of mevrouw,

Sinds de update van IOS 17.0.2 liggen al mijn home accessoires eruit. Alle accessoires geven aan dat ze unreachable zijn. Ik heb de Homey app al diverse malen opnieuw proberen te installeren. In het begin functioneert alles maar naar een korte periode staat alles weer op unreachable. Heeft u vaker van dit probleem gehoord en is hier een oplossing voor?

met vriendelijke groet,

Mark

**Comment by robertklep** [comment]
Heb je Home Hub devices (Apple TV of HomePod)? Zo ja, zorg er dan voor dat die up-to-date zijn, en reboot ze een keer.

Overigens zou ik aanraden om over te stappen naar de [HomeKitty app](https://homey.app/nl-nl/app/name.klep.homekitty/HomeKitty/), de HomeyKit app is verouderd en wordt niet meer onderhouden.

**Comment by mvancaulil** [comment]
Ja ik heb een apple tv. Maar het is met name voor mijn Homey van Athom. Dan heb ik er niet zoveel aan dat ik alleen maar flows kan bedienen met de homekitty app. Of kan dit wel?

**Comment by robertklep** [comment]
Ik zeg natuurlijk niet voor niets dat je je Apple TV moet rebooten, want 9 van de 10 keer als apparaten unreachable zijn ligt dat aan een Home hub, zoals een Apple TV, die problemen geeft.

HomeKitty is een app die draait op Homey, net als HomeyKit, de app waarvoor je nu hier een issue hebt gepost. Maar HomeyKit wordt niet meer onderhouden en is vervangen voor HomeKitty, vandaar dat ik het noem.

**Comment by mvancaulil** [comment]
Beste Robbert,

Bedankt voor de heldere uitleg. Het is inmiddels gelukt met de app Homeykitty en tot nu toe werkt alles weer. Op de Sonos speakers na. Maar dat is niet erg.

mvg. Mark
