### ISSUE TITLE
Add Velux active with Netamo Support

### ISSUE THREAD

**Issue by Wismerill** [swttt/com.swttt.homekit#261]
Hey is it possible to add Velux Active with Netamo ?
In log we can see the Velux Bridge but once installed there is no device visible

**Comment by robertklep** [comment]
HomeyKit is not being maintained anymore.

I would suggest migrating to the HomeKitty app, which supports more devices and is still being actively maintained. If your device doesn't work with it, you can ask for device support [here](https://github.com/robertklep/name.klep.homekitty/issues/new?assignees=&labels=&projects=&template=feature-request-unsupported-device.md&title=%5BFeature+Request%2FUnsupported%5D).
