### ISSUE TITLE
Feature request: Possibility to add "virtual devices" that starts a flow?

### ISSUE THREAD

**Issue by mvunen** [swttt/com.swttt.homekit#3]
Based on presence Homey starts multiple actions in one flow (HTTP request flowkaarten). Sometimes I like to start a flow manually. I think its great to have the ability to start a flow via a press on one button. Is this possible with Homekit?

**Comment by mvunen** [comment]
Sorry, I already get this done with Better Logic.
Create a Boolean that functioning like a switch On or Off.
Then add device, select Better Logic icon => bit switch => select boolean just created.
Create flow with this device... to then activate flow or trigger web requests...

Working great, I can now (de)activate my alarm manually! Yeahhh!!

**Comment by swttt** [comment]
Great! 😀
I'll close this, you can re-open if it isn't working as expected.

**Comment by peblin** [comment]
I like mvunen's solution, but I also think it would be tremendously useful if there was an option in the HomeyKit settings of the kind "expose (these) flows as buttons" - basically just simulating an on button in HomeKit that triggers a flow.
That way, flow's that I've set up to light up my living room using wall switches and remotes will work directly from HomeKit without the need for setting up scenes or using Better Logic.

**Comment by swttt** [comment]
You can't trigger flows directly. But the current version does support buttons. (switches back to off state)

**Comment by peblin** [comment]
Ok, thanks!
