### ISSUE TITLE
Problem with removing a device

### ISSUE THREAD

**Issue by daneedk** [swttt/com.swttt.homekit#31]
I've added a Aeotec MultiSensor 6 to homekit, and it seems to work OK, but upon removing something does not work as expected. I've tried it several times, the result is the same, Homey says 'Trying to remove device undefined' followed by 'undefined is removed!' but the device is not removed.

Log:
![image](https://user-images.githubusercontent.com/16610696/31385794-c4d70aa8-adc4-11e7-96ae-881954789cef.png)

Status of device after trying to delete:
![image](https://user-images.githubusercontent.com/16610696/31385910-3e60f2e4-adc5-11e7-923e-65f0e5e31eda.png)

**Comment by swttt** [comment]
New version isn't using the "old" settings anymore. So that counts as fixed in the current release :)
