### ISSUE TITLE
[1.0.14] Filter in HomeyKit setting not working correctly

### ISSUE THREAD

**Issue by bm480** [swttt/com.swttt.homekit#34]
In order to add only some of my 40 devices, I use the filter to search for devices starting with for example the letters STU (for study). However, I also get devices named as follows:

TUI Loungehoek lamp (in Achtertuin)
INL Multisensor (in Inloopkast)
INL Plafondlamp (in Inloopkast)
etc.

**Comment by swttt** [comment]
That is actually intended (for typo's etc.)
When you type STU it gives the results because it matched 2 of de 3 letters:
**TU**I Loungehoek lamp (in Achtertuin)
INL Plafondlamp (in Inloopka**st**)
INL Multisensor (in Inloopka**st**)

**Comment by bm480** [comment]
Ok, reasonable enough. But in general I use the filter to limit the number of items to only a few. Getting more items than asked for interferes with my goal. My thought is that since the filter works in real time, it is not necessary to accommodate for spelling mistakes as it is perfectly clear what happens after typing each character. But that is just my two cents... ;^)

**Comment by swttt** [comment]
Valid point.
But other then fixing typos it also makes it easy to search for device class and zone name as well 😀
