### ISSUE TITLE
Accessoires not visible iPhone 

### ISSUE THREAD

**Issue by hrc007** [swttt/com.swttt.homekit#40]
Homey version: 1.5.5
Homeykit version: 2.04
Iphone 5se ios: 11.0.3

After i installed the beta app, i paired via the procedure used the code 200.20.200 but my iPhone dont see any assesoires.

(Btw the description procedure in the appstore doesnt show the image of paircode on my ipad)

**Comment by hrc007** [comment]
I just did a re-install but i did not fixed it!.
In the old homeykit i saw in the settings menu within homey a homeykit settings menu were you could Add devices. In the beta release this menu is not available?

**Comment by bm480** [comment]
Hi, tried to install the beta but athom cli complained:

$ athom project --install .
1/3 - Archiving...
2/3 - Uploading to Mijn Homey @ 192.168.2.68:80...
**missing ./settings/index.html**

Tried to use the old index.html but this led to strange behaviour in the Homey App settings.

Note: in the GitHub code page, I can't see the code image anymore...

**Comment by swttt** [comment]
@bm480 
You are sure that you are installing the beta branch and not the master? 😁

**Comment by swttt** [comment]
Found the issue and fixed it. Current beta branch on GitHub should work. New beta in the appstore is awaiting approval 😀

If it's not fixed in 2.0.5 please re-open.

**Comment by bm480** [comment]
Just installed the beta branch without any hassle. Looks good! 👍

**Comment by hrc007** [comment]
Ok Thanks i will wait for the Appstore release!
