### ISSUE TITLE
Wrong colors for colored light 

### ISSUE THREAD

**Issue by bm480** [swttt/com.swttt.homekit#42]
I have a few RGB led lights which are added to HomeKit. When changing the light color to blue, the color picker in HomeKit shows purple. When the color picker selects green, the lights go red. To make the lights green, the color picker should be set at orange.

When I look in the Homey app itself, the color shown in the app matches the lights themselves.

**Comment by swttt** [comment]
Oops...good call. Forgot to convert those numbers. Did noticed the strange colors on testing tho...but blamed the zigbee driver for it 😁 

Will be fixed in the next release

**Comment by swttt** [comment]
Fixed in current Alpha

**Comment by bm480** [comment]
I have re-installed the latest beta (v2.0.7) and the color issue seems fixed. 

However, picking the right color is not always as easy as it should be. Especially when the light is turned on (and I have two of these lights grouped together in HomeKit). The color selection screen in HomeKit is comprised of a Color screen and a Temperature screen. When changing the color you need to put your finger on the color wheel, the light color is changing as your finger slides over different colors on the screen. But sometimes randomly the screen switches to Temperature before you have the opportunity to confirm the picked color. I also tried changing the color while the lights were turned off, which gave somewhat better results. I suspect that when the color of the lights are changed, feedback messages are causing this weird behaviour.

**Comment by bm480** [comment]
For the record, I'm using Zipato RGB bulbs.

**Comment by swttt** [comment]
Ye noticed the same thing and wondered what is causing it.
I think when the Hue and Saturation get changed, it gets a realtime update from the Temperature as well (that keeps the same). 

Will look into it tonight.
