### ISSUE TITLE
Feature request: (generic) sensor device

### ISSUE THREAD

**Issue by RobinBol** [swttt/com.swttt.homekit#51]
To be able to use sensor devices in HomeKit a generic sensor device should be created which can take a various amount of sensor capabilities (e.g.: `measure_temperature`, `measure_humidity`, `measure_luminance`, et cetera). Not sure how HomeKit handles sensor devices with varying capabilities though.

**Comment by swttt** [comment]
Only certain charasteristics can be bound to certain services. For example the motion sensor and temperature measurement need to be two differenct services. (and show up as two different devices)

For that reason most sensors are split into different components e.g. motion sensor, contact sensor etc. with the added capabilities those sensors could have. Sure.. i'll miss some. But at that time it seamed the most obv way.

Any reason why it would be easier to implement it as one device type / component?

**Comment by RobinBol** [comment]
Ah, well like I said, I am not sure how HomeKit handles sensor devices with varying capabilities, but the problem I am currently experiencing is that devices of class `sensor` with only the capabilities `measure_temperature`, `measure_pressure` and `measure_humidity` do not show up as devices in HomeKit.

**Comment by swttt** [comment]
It actually should add as 2 different devices. One temperature and one humidity.
Creating it as one "device type" still kinda needs the same checks as it does now in the app.js .

Will think it through tho, there might be a better solution indeed.

**Comment by swttt** [comment]
Gave it some thought, but maybe you could give your opinion on this as well:

- Every item in /lib/devices should be an exact match to a Homey class
- Within this class there are predefined capabilities that should be looped/checked vs the device
- On the `other` class all possible capabilities should be looped

Anything i didn't consider or forget?

**Comment by RobinBol** [comment]
Hm well, I think (if possible) it is better to look at individual capabilities instead of device class only, since in Homey a device with device class `socket` can also have the `measure_temperature` capability for example. However, I guess this will be more complicated/not possible with the way homekit is constructed (but that is something you know more about than me).

**Comment by swttt** [comment]
At least all sensors are into one file, and should support all of them (each capability should be added).
Thanks to @nhassink tho.

I'll close this one, since i don't think there is any other way to improve this at the moment.
