### ISSUE TITLE
Feature request: Add support for fibaro wall plug

### ISSUE THREAD

**Issue by mansica** [swttt/com.swttt.homekit#53]
It would be nice to have support for Fibaro wall plug.

**Comment by swttt** [comment]
Might depend on how you added the plug (what class you have chosen).
But it should actually work as a light and regular switch already.

**Comment by Veldkornet** [comment]
I have several and they work fine

**Comment by swttt** [comment]
Closing this issue since it should work.
If thats really not the case, then you can re-open it.
