### ISSUE TITLE
Dont work after last update

### ISSUE THREAD

**Issue by Patrikgolfer** [swttt/com.swttt.homekit#55]
all devices offline after last update. Delete and tried to reinstall but cant find it in my Iphone after I entered the pairing code

**Comment by Gobbomaster** [comment]
I have exactly the same problem. No response from any device after the update (including homey-bridge). Restarted the app but can't find the homey anymore on my Iphone.

**Comment by realmnm** [comment]
I have the same problem. No response from any of the devices that is connected via the Homey. I have on plug that is connected directly to homekit and that one works so there is no problem with the appletv. I got this problem after updating to the latest version.

**Comment by GrimmJok3r** [comment]
Same issue here.
After auto update devices not responding in HomeKit
removed Bridge, tried to add it again not connecting
restarted Homey no luck
removed HomeyKit and reinstall still no luck

the wife is gonna be pissed

**Comment by Bloke63** [comment]
Same here, updated all my iOS devices to 11.2.5. The connection was lost after the pushed update of Homeykit 2.0.8. Restarted Homey several times, removed hub from HomeKit, removed Homeykit completly and reinstalled. There seems to be no way to reconnect the Homeykit hub to HomeKit again.
Beta Homey Firmware Versie: 1.5.6-rc.8.  

Anyway I can help to bring it to life again Bas?

**Comment by swttt** [comment]
Currently a PR with bug fixes is awaiting approval for the beta branch. (2.0.9)

**Comment by swttt** [comment]
Beta is published, could you guys test before i push it to stable?

**Comment by laurenssss** [comment]
removed Homey from homekit during the failure, but now it seems it is not discovered anymore when I add it again

**Comment by swttt** [comment]
Can someone test this running from the CLI (current code is in the alpha branch) and post the log output here?

**Comment by realmnm** [comment]
I did the upgrade to 2.0.9 without removing anything. But I get the same error (No Response) from all my devices that is attached to the Homey.

**Comment by swttt** [comment]
Current Alpha branch should work, and it's awaiting approval.

**Comment by laurenssss** [comment]
CLI install is working like a charm!

**Comment by Bloke63** [comment]
Tried running the App from CLI after downloading the master. Maybe I'm doing somthing wrong

missing ./settings/index.html

however the file is available in

**Comment by swttt** [comment]
You should download the alpha branch and not the master :)

**Comment by Bloke63** [comment]
Yep, Sorry. Mea Culpa

Alpha is running nicely. 

Where can I find the log files, if you like to have them?

**Comment by swttt** [comment]
You could use `athom project --run` this will run the app on Homey and outputs the logs into the console.

**Comment by Bloke63** [comment]
Got the console running. How can I report them in private to you

**Comment by swttt** [comment]
Best way is using Slack and send me a DM. Not sure if it's still implemented in Homey but there was a way to report so a developer on the settings->apps page.

**Comment by swttt** [comment]
Current update should fix the issue, and is aproved in the appstore.
Closing this now.
