### ISSUE TITLE
[Feature Request] Exclude Devices

### ISSUE THREAD

**Issue by Veldkornet** [swttt/com.swttt.homekit#62]
I have a few devices which are already added to HomeKit like my Philips Hue.

Now, all of my Hue lamps are added again, but now via HomeyKit. So I have 2x each lamp.

As another example, my Somfy sunscreen outside is reversed (so when it's closed it's says it's open, and visa versa). So I made a "Virtual Sunscreen" to reverse the operation, but now HomeyKit added both. Now I have a warning on my homescreen that the sunscreen is always open.

So again, could you add the possability please to exclude some devices?

**Comment by kerkenit** [comment]
I have devices in Homey I don't want to control by HomeKit so I als want to exclude some devices

**Comment by TonD83** [comment]
Yes, please. This is the only reason I still use the other HomeKit app. Hope this can be added in the near future so I can switch :)
