### ISSUE TITLE
xiaomi aqara humidity sensor

### ISSUE THREAD

**Issue by nickvandergraaf** [swttt/com.swttt.homekit#79]
Is it posible to add the Humidity sensor in Homekit?

Kind regards,

Nick

**Comment by nhassink** [comment]
It should already work. My aqara sensors show up in HomeKit. Note that they are added as separate sensors (one temperature and one humidity), this is a limitation of HomeKit. The Atmospheric pressure is not supported by HomeKit either

**Comment by nickvandergraaf** [comment]
Sorry that is what i mean.
The Atmospheric sensor.

Op 20 mei 2018 om 07:13 heeft nhassink <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


It should already work. My aqara sensors show up in HomeKit. Note that they are added as separate sensors (one temperature and one humidity), this is a limitation of HomeKit. The Atmospheric pressure is not supported by HomeKit either

**Comment by nhassink** [comment]
That is not possible at the moment because there is no atmospheric pressure sensor in HomeKit. Apple first has to add this to HomeKit before homeykit can use it.

**Comment by nickvandergraaf** [comment]
Okay maybe in the future.
Thanks
