### ISSUE TITLE
[1.0.4] Suddenly devices doesn't answer

### ISSUE THREAD

**Issue by marklajer** [swttt/com.swttt.homekit#8]
After 1.0.3 and 1.0.4 update the devices in Home app doesn't answer 

In 1.0.4 it happened after 4 hours
In 1.0.3 it happened after 2 hours

The homey bridge is visible and online in Home app but all devices are offline. 

- If I restart HomeyKit nothing happens. 
- If I restart Homey the bridge is Offline + alle devices.

No errors in log - tried from different iOS devices. 

The only solution right now is to delete Homey bridge from Home app, delete HomeyKit on Homey - install it again and start over.

**Comment by swttt** [comment]
Seems related to https://github.com/swttt/com.swttt.homekit/issues/5

**Comment by swttt** [comment]
Closing this since its a duplicate.
