### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by kapusticka** [swttt/com.swttt.homekit#88]
It’s possible to add charts for apple HomeKit devices to Athom Homey? For example temperatures from radiator valves or humidity sensor.

**Comment by robertklep** [comment]
Not sure if you mean devices that are controlled by HomeKit but not by Homey, or devices that are controlled by Homey _and_ exposed to HomeKit.

In case of the former: that's sadly not possible.

In case of the latter: Homey has its Insights feature for that.
