### ISSUE TITLE
Fibaro.

### ISSUE THREAD

**Issue by gaudiops** [swttt/com.swttt.homekit#89]

**Comment by gaudiops** [comment]
Great app! I use HomeKit a lot, so in very grateful. I was sondering about 1 thing, the app says buttons are supported, but a zwave plus fibaro button installa perfect in homey, but is the onlangs device i cant see in homeyapp?

**Comment by robertklep** [comment]
Assuming that you mean the FGPB-101 device: looking at the [driver code](https://github.com/athombv/com.fibaro/blob/3ebd520720d5ce0687996426f7dffa5eb7aef3cf/drivers/FGPB-101/driver.js) and the device configuration, the device is configured as a "sensor" with only one capability, "measure_battery".

That's not enough for HomeyKit to be able to recognize and use the device.
