### ISSUE TITLE
Fibaro roller shutter 2 "fully open read 99%"

### ISSUE THREAD

**Issue by akke911** [swttt/com.swttt.homekit#91]
Fibaro roller shutter 2:
Fully open curtains read 99% in HomeKit. 

Homekit app v2.1.0
Fibaro app v1.5.18
Homey Firmware Version: 1.5.13-rc.11

**Comment by robertklep** [comment]
Looking at [the code for blinds](https://github.com/swttt/com.swttt.homekit/blob/master/lib/devices/dimblinds.js), Homeykit just multiplies the value it receives from Homey by 100, so my guess is that Homey internally sends a value of "0.99" for some reason. 

However, I don't have blinds, so can't confirm. If so, there's not much we can do about it though.

**Comment by akke911** [comment]
Thanks, you are right. Checking "tags" dim value in flow, and there are some strangeness going on.
Looking at com.fibaro/drivers/FGR-222/driver.js line 88 , it seems it sets value 0.99 when it should be 1.

`				if (value >= 1) {
					if (invertDirection) value = 0;
					else value = 0.99;
				}`

I'll report it. Thanks again.

**Comment by robertklep** [comment]
Thanks! Closing for now, feel free to open if we need to do anything :)
