### ISSUE TITLE
AEOTEC garage kit 

### ISSUE THREAD

**Issue by anthonycorso69** [swttt/com.swttt.homekit#92]
When I open garage, home kit reports closed, when I close garage, home kit reports open - I would be grateful if this could be fixed. :)

**Comment by robertklep** [comment]
It's a [known issue](https://github.com/athombv/homey/issues/2568) for the Aeotec driver: it reports the opposite state for locked/unlocked.

That's not something that we can fix :(

**Comment by nhassink** [comment]
A workaround for this issue might be to add a virtual device (with the app virtual devices) and change the state (up/down) of this virtual device in a flow based on the inverted state of the Aeotec device and vice versa. If this works you can use the virtual device in HomeKit.
