### ISSUE TITLE
Not updating Room (Position) name

### ISSUE THREAD

**Issue by DIYglenn** [swttt/com.swttt.homekit#95]
I renamed all my rooms, and while HomeyKit works fine, the room name under each sensor is still the old one. Probably because it is only checked when first added?

<del>Will try reinstall, which probably "refreshes" the names, but thought I'd add the issue anyways.</del>
Nope...

**Comment by robertklep** [comment]
Homeykit doesn't have explicit code that deals with how you configure rooms in the Home app on iOS.

You could try and restart the Homeykit app to see if that triggers iOS to re-assign the devices to the new roomname, but there's not much that we can do on the side of Homeykit

**Comment by DIYglenn** [comment]
You're right. 
I think this is a problem with Homey in general. I noticed that this is an issue with several apps, and will probably have to be solved by Athom.

Thanks!
