### ISSUE TITLE
Homey 2.0

### ISSUE THREAD

**Issue by fkooten** [swttt/com.swttt.homekit#96]
Is Homeykit ready for Homey 2.0.
I am using 2.0 and Home is not connected anymore

**Comment by robertklep** [comment]
> Is Homeykit ready for Homey 2.0.

No, it isn't. From what I understand, apps that use the Web API are not yet supported by the current 2.0 RC, and Homeykit is one of those apps.

Homey now has Homekit-support built-in (although it's limited in terms of app/device support in comparison with Homeykit), perhaps that's an option to check out.

**Comment by nhassink** [comment]
The beta branch is V2 compatible
