### ISSUE TITLE
Control HomeKit enabled devices with Homey (other way around)

### ISSUE THREAD

**Issue by LanMart** [swttt/com.swttt.homekit#97]
Hi,

Is it also possible to control HomeKit enabled devices with Homey using this app?
(e.g. my honeywell lyric t6 thermostat is HomeKit enabled, but cannot be connected to homey,  it is questionable if the only honeywell app available supports my thermostat)

So this may be a feature request to use the app to work the other way around.

Thanks in advance for your help,

Martijn

**Comment by robertklep** [comment]
No, that's not possible, and I don't think there's an app that can do this.

I've been wanting to look into this myself though, because it _is_ a really cool idea.

**Comment by robertklep** [comment]
I started working on an app for this: https://github.com/robertklep/name.klep.homekit-client

Closing this issue.
